In [1]:
import pandas as pd
import numpy as np

In [15]:
# till now
# TimeStamp
pd.Timestamp('6th jan 2026 8:09')
# DateTimeIndex->df and series index
pd.DatetimeIndex([pd.Timestamp('6th jan 2026 8:09'),pd.Timestamp('16th jun 2026 9:19'),pd.Timestamp('6th Aug 2026 10:09')])

# date range()
pd.date_range(start='2023-1-6',end='2023-1-31',freq='D')
# to_datetime()
s=pd.Series(['2026/1/7','2026/1/8','2026/1/9'])
pd.to_datetime(s).dt.day_name()

0    Wednesday
1     Thursday
2       Friday
dtype: object

# Timedelta Object
- Represents a duration  the difference b/w two dates or times

In [16]:
# create using timestamp
t1=pd.Timestamp('1st Jul 2026 2:56:45')
t2=pd.Timestamp('14th Jul 2026 8:27:29')
t1-t2

Timedelta('-14 days +18:29:16')

In [17]:
# standalone creation
pd.Timedelta(days=2,hours=10,minutes=35)

Timedelta('2 days 10:35:00')

In [18]:
# Arithmetic
pd.Timestamp('1st Jul 2026')+pd.Timedelta(days=12,hours=9,minutes=90)

Timestamp('2026-07-13 10:30:00')

In [19]:
pd.date_range(start='2025-2-2',end='2026-2-4',freq='D')-pd.Timedelta(days=12,hours=9,minutes=90)

DatetimeIndex(['2025-01-20 13:30:00', '2025-01-21 13:30:00',
               '2025-01-22 13:30:00', '2025-01-23 13:30:00',
               '2025-01-24 13:30:00', '2025-01-25 13:30:00',
               '2025-01-26 13:30:00', '2025-01-27 13:30:00',
               '2025-01-28 13:30:00', '2025-01-29 13:30:00',
               ...
               '2026-01-13 13:30:00', '2026-01-14 13:30:00',
               '2026-01-15 13:30:00', '2026-01-16 13:30:00',
               '2026-01-17 13:30:00', '2026-01-18 13:30:00',
               '2026-01-19 13:30:00', '2026-01-20 13:30:00',
               '2026-01-21 13:30:00', '2026-01-22 13:30:00'],
              dtype='datetime64[ns]', length=368, freq='D')

In [26]:
# real life example
df=pd.read_csv("E:\data\data_set\deliveries.csv")
df

    order_date delivery_date
0      5/24/98        2/5/99
1      4/22/92        3/6/98
2      2/10/91       8/26/92
3      7/21/92      11/20/97
4       9/2/93       6/10/98
..         ...           ...
496    6/24/91        2/2/96
497     9/9/91       3/30/98
498   11/16/90       4/27/98
499     6/3/93       6/13/93
500     1/4/90       10/3/91

[501 rows x 2 columns]

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_date     501 non-null    object
 1   delivery_date  501 non-null    object
dtypes: object(2)
memory usage: 8.0+ KB

In [28]:
df['order_date']=pd.to_datetime(df['order_date'])
df['delivery_date']=pd.to_datetime(df['delivery_date'])

C:\Users\USER\AppData\Local\Temp\ipykernel_4728\3502913937.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['order_date']=pd.to_datetime(df['order_date'])
C:\Users\USER\AppData\Local\Temp\ipykernel_4728\3502913937.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['delivery_date']=pd.to_datetime(df['delivery_date'])

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_date     501 non-null    datetime64[ns]
 1   delivery_date  501 non-null    datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 8.0 KB

In [30]:
df['delivery_time_period']=df['delivery_date']-df['order_date']
df['delivery_time_period'].mean()

Timedelta('1217 days 22:53:53.532934128')

### Time series

A time series is a data set that tracks a sample over time. In particular, a time series allows one to see what factors influence certain variables from period to period. Time series analysis can be useful to see how a given asset, security, or economic variable changes over time.

Examples

- Financial Data (Company stocks)
- Natural Data (Rainfall measurement)
- Event Data (Covid)
- Medical Data (Heart rate monitoring)

Types of Operations done on Time Series

- Time Series Analysis
- Time Series Forecasting

In [31]:
google=pd.read_csv("E:\data\data_set\google.csv")
google.head()

         Date       Open       High        Low      Close  Adj Close    Volume
0  2004-08-19  49.813290  51.835709  47.800831  49.982655  49.982655  44871361
1  2004-08-20  50.316402  54.336334  50.062355  53.952770  53.952770  22942874
2  2004-08-23  55.168217  56.528118  54.321388  54.495735  54.495735  18342897
3  2004-08-24  55.412300  55.591629  51.591621  52.239197  52.239197  15319808
4  2004-08-25  52.284027  53.798351  51.746044  52.802086  52.802086   9232276

In [32]:
google.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
4466,2022-05-16,2307.679932,2332.149902,2286.699951,2295.850098,2295.850098,1164100
4467,2022-05-17,2344.550049,2344.550049,2306.750000,2334.030029,2334.030029,1078800
4468,2022-05-18,2304.750000,2313.913086,2242.840088,2248.020020,2248.020020,1399100
4469,2022-05-19,2236.820068,2271.750000,2209.360107,2214.909912,2214.909912,1459600
4470,2022-05-20,2241.709961,2251.000000,2127.459961,2186.260010,2186.260010,1878100

In [33]:
login=pd.read_csv("E:\data\data_set\login.csv")

In [34]:
login.head()

   1  466  2017-01-07 18:24:07 Unnamed: 3
0  2  466  2017-01-07 18:24:55        NaN
1  3  458  2017-01-07 18:25:18        NaN
2  4  458  2017-01-07 18:26:21        NaN
3  5  592  2017-01-07 19:09:59        NaN
4  6  393  2017-01-08 00:41:19        NaN

In [36]:
login.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3002 entries, 0 to 3001
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   1                    3002 non-null   int64
 1   466                  3002 non-null   int64
 2   2017-01-07 18:24:07  3002 non-null   object
 3   Unnamed: 3           2209 non-null   object
dtypes: int64(2), object(2)
memory usage: 93.9+ KB

In [38]:
login.drop(['Unnamed: 3'],axis=1,inplace=True)

In [40]:
login.head()

   1  466  2017-01-07 18:24:07
0  2  466  2017-01-07 18:24:55
1  3  458  2017-01-07 18:25:18
2  4  458  2017-01-07 18:26:21
3  5  592  2017-01-07 19:09:59
4  6  393  2017-01-08 00:41:19

KeyError: 'Requested level (1) does not match index name (None)'