In [3]:
import requests
import pandas as pd
import time
API_KEYS="8265bd1679663a7ea12ac168da84d2e8"
BASE_URL = "https://api.themoviedb.org/3/movie/top_rated"

all_movies=[]

for page in range(1,472):
    url=f"{BASE_URL}?api_key={API_KEYS}&language=en-US&page{page}"

    response=requests.get(url)

    if response.status_code==200:
        data=response.json()
        all_movies.extend(data['results'])
        print(f"Page {page} done")

    else:
        print(f"Error on page {page}")

    time.sleep(0.2) # avoid hitting rate limits
df=pd.DataFrame(all_movies)

Page 1 done
Page 2 done
Page 3 done
Page 4 done
Page 5 done
Page 6 done
Page 7 done
Page 8 done
Page 9 done
Page 10 done
Page 11 done
Page 12 done
Page 13 done
Page 14 done
Page 15 done
Page 16 done
Page 17 done
Page 18 done
Page 19 done
Page 20 done
Page 21 done
Page 22 done
Page 23 done
Page 24 done
Page 25 done
Page 26 done
Page 27 done
Page 28 done
Page 29 done
Page 30 done
Page 31 done
Page 32 done
Page 33 done
Page 34 done
Page 35 done
Page 36 done
Page 37 done
Page 38 done
Page 39 done
Page 40 done
Page 41 done
Page 42 done
Page 43 done
Page 44 done
Page 45 done
Page 46 done
Page 47 done
Page 48 done
Page 49 done
Page 50 done
Page 51 done
Page 52 done
Page 53 done
Page 54 done
Page 55 done
Page 56 done
Page 57 done
Page 58 done
Page 59 done
Page 60 done
Page 61 done
Page 62 done
Page 63 done
Page 64 done
Page 65 done
Page 66 done
Page 67 done
Page 68 done
Page 69 done
Page 70 done
Page 71 done
Page 72 done
Page 73 done
Page 74 done
Page 75 done
Page 76 done
Page 77 done
Page 78 done
Page 79 done
Page 80 done
Page 81 done
Page 82 done
Page 83 done
Page 84 done
Page 85 done
Page 86 done
Page 87 done
Page 88 done
Page 89 done
Page 90 done
Page 91 done
Page 92 done
Page 93 done
Page 94 done
Page 95 done
Page 96 done
Page 97 done
Page 98 done
Page 99 done
Page 100 done
Page 101 done
Page 102 done
Page 103 done
Page 104 done
Page 105 done
Page 106 done
Page 107 done
Page 108 done
Page 109 done
Page 110 done
Page 111 done
Page 112 done
Page 113 done
Page 114 done
Page 115 done
Page 116 done
Page 117 done
Page 118 done
Page 119 done
Page 120 done
Page 121 done
Page 122 done
Page 123 done
Page 124 done
Page 125 done
Page 126 done
Page 127 done
Page 128 done
Page 129 done
Page 130 done
Page 131 done
Page 132 done
Page 133 done
Page 134 done
Page 135 done
Page 136 done
Page 137 done
Page 138 done
Page 139 done
Page 140 done
Page 141 done
Page 142 done
Page 143 done
Page 144 done
Page 145 done
Page 146 done
Page 147 done
Page 148 done
Page 149 done
Page 150 done
Page 151 done
Page 152 done
Page 153 done
Page 154 done
Page 155 done
Page 156 done
Page 157 done
Page 158 done
Page 159 done
Page 160 done
Page 161 done
Page 162 done
Page 163 done
Page 164 done
Page 165 done
Page 166 done
Page 167 done
Page 168 done
Page 169 done
Page 170 done
Page 171 done
Page 172 done
Page 173 done
Page 174 done
Page 175 done
Page 176 done
Page 177 done
Page 178 done
Page 179 done
Page 180 done
Page 181 done
Page 182 done
Page 183 done
Page 184 done
Page 185 done
Page 186 done
Page 187 done
Page 188 done
Page 189 done
Page 190 done
Page 191 done
Page 192 done
Page 193 done
Page 194 done
Page 195 done
Page 196 done
Page 197 done
Page 198 done
Page 199 done
Page 200 done
Page 201 done
Page 202 done
Page 203 done
Page 204 done
Page 205 done
Page 206 done
Page 207 done
Page 208 done
Page 209 done
Page 210 done
Page 211 done
Page 212 done
Page 213 done
Page 214 done
Page 215 done
Page 216 done
Page 217 done
Page 218 done
Page 219 done
Page 220 done
Page 221 done
Page 222 done
Page 223 done
Page 224 done
Page 225 done
Page 226 done
Page 227 done
Page 228 done
Page 229 done
Page 230 done
Page 231 done
Page 232 done
Page 233 done
Page 234 done
Page 235 done
Page 236 done
Page 237 done
Page 238 done
Page 239 done
Page 240 done
Page 241 done
Page 242 done
Page 243 done
Page 244 done
Page 245 done
Page 246 done
Page 247 done
Page 248 done
Page 249 done
Page 250 done
Page 251 done
Page 252 done
Page 253 done
Page 254 done
Page 255 done
Page 256 done
Page 257 done
Page 258 done
Page 259 done
Page 260 done
Page 261 done
Page 262 done
Page 263 done
Page 264 done
Page 265 done
Page 266 done
Page 267 done
Page 268 done
Page 269 done
Page 270 done
Page 271 done
Page 272 done
Page 273 done
Page 274 done
Page 275 done
Page 276 done
Page 277 done
Page 278 done
Page 279 done
Page 280 done
Page 281 done
Page 282 done
Page 283 done
Page 284 done
Page 285 done
Page 286 done
Page 287 done
Page 288 done
Page 289 done
Page 290 done
Page 291 done
Page 292 done
Page 293 done
Page 294 done
Page 295 done
Page 296 done
Page 297 done
Page 298 done
Page 299 done
Page 300 done
Page 301 done
Page 302 done
Page 303 done
Page 304 done
Page 305 done
Page 306 done
Page 307 done
Page 308 done
Page 309 done
Page 310 done
Page 311 done
Page 312 done
Page 313 done
Page 314 done
Page 315 done
Page 316 done
Page 317 done
Page 318 done
Page 319 done
Page 320 done
Page 321 done
Page 322 done
Page 323 done
Page 324 done
Page 325 done
Page 326 done
Page 327 done
Page 328 done
Page 329 done
Page 330 done
Page 331 done
Page 332 done
Page 333 done
Page 334 done
Page 335 done
Page 336 done
Page 337 done
Page 338 done
Page 339 done
Page 340 done
Page 341 done
Page 342 done
Page 343 done
Page 344 done
Page 345 done
Page 346 done
Page 347 done
Page 348 done
Page 349 done
Page 350 done
Page 351 done
Page 352 done
Page 353 done
Page 354 done
Page 355 done
Page 356 done
Page 357 done
Page 358 done
Page 359 done
Page 360 done
Page 361 done
Page 362 done
Page 363 done
Page 364 done
Page 365 done
Page 366 done
Page 367 done
Page 368 done
Page 369 done
Page 370 done
Page 371 done
Page 372 done
Page 373 done
Page 374 done
Page 375 done
Page 376 done
Page 377 done
Page 378 done
Page 379 done
Page 380 done
Page 381 done
Page 382 done
Page 383 done
Page 384 done
Page 385 done
Page 386 done
Page 387 done
Page 388 done
Page 389 done
Page 390 done
Page 391 done
Page 392 done
Page 393 done
Page 394 done
Page 395 done
Page 396 done
Page 397 done
Page 398 done
Page 399 done
Page 400 done
Page 401 done
Page 402 done
Page 403 done
Page 404 done
Page 405 done
Page 406 done
Page 407 done
Page 408 done
Page 409 done
Page 410 done
Page 411 done
Page 412 done
Page 413 done
Page 414 done
Page 415 done
Page 416 done
Page 417 done
Page 418 done
Page 419 done
Page 420 done
Page 421 done
Page 422 done
Page 423 done
Page 424 done
Page 425 done
Page 426 done
Page 427 done
Page 428 done
Page 429 done
Page 430 done
Page 431 done
Page 432 done
Page 433 done
Page 434 done
Page 435 done
Page 436 done
Page 437 done
Page 438 done
Page 439 done
Page 440 done
Page 441 done
Page 442 done
Page 443 done
Page 444 done
Page 445 done
Page 446 done
Page 447 done
Page 448 done
Page 449 done
Page 450 done
Page 451 done
Page 452 done
Page 453 done
Page 454 done
Page 455 done
Page 456 done
Page 457 done
Page 458 done
Page 459 done
Page 460 done
Page 461 done
Page 462 done
Page 463 done
Page 464 done
Page 465 done
Page 466 done
Page 467 done
Page 468 done
Page 469 done
Page 470 done
Page 471 done

In [4]:
df.head()

   adult                     backdrop_path        genre_ids  ...  video vote_average vote_count
0  False  /zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg         [18, 80]  ...  False        8.718      30065
1  False  /tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg         [18, 80]  ...  False        8.687      22707
2  False  /kGzFbGhp99zva6oZODW5atUtnqi.jpg         [18, 80]  ...  False        8.572      13755
3  False  /zb6fM1CX41D9rF9hdgclu0peUmy.jpg  [18, 36, 10752]  ...  False        8.567      17283
4  False  /xyWKrni8WrYzqn7ztvI5nIY0h62.jpg      [35, 10749]  ...  False        8.558        309

[5 rows x 14 columns]

# Faster way to get data-(parallel request)

In [7]:
import pandas as pd
from concurrent.futures import ThreadPoolExecutor
import requests
API_KEYS="8265bd1679663a7ea12ac168da84d2e8"
BASE_URL = "https://api.themoviedb.org/3/movie/top_rated"

def fetch_page(page):
    url=f"{BASE_URL}?api_key={API_KEYS}&language=en-US&page={page}"
    response=requests.get(url)

    if response.status_code==200:
        return response.json()['results']
    return []

with ThreadPoolExecutor(max_workers=10) as executor:
    results=executor.map(fetch_page,range(1,472))
all_movies=[movie for page in results for movie in page]

In [9]:
df=pd.json_normalize(all_movies)

In [10]:
API_KEY="8265bd1679663a7ea12ac168da84d2e8"
url= f"https://api.themoviedb.org/3/genre/movie/list?api_key={API_KEY}&language=en-US"
response=requests.get(url)
data=response.json()
# create dictionary : {id:name}

genge_dict={genre['id']:genre['name'] for genre in data['genres']}
genge_dict

{28: 'Action',
 12: 'Adventure',
 16: 'Animation',
 35: 'Comedy',
 80: 'Crime',
 99: 'Documentary',
 18: 'Drama',
 10751: 'Family',
 14: 'Fantasy',
 36: 'History',
 27: 'Horror',
 10402: 'Music',
 9648: 'Mystery',
 10749: 'Romance',
 878: 'Science Fiction',
 10770: 'TV Movie',
 53: 'Thriller',
 10752: 'War',
 37: 'Western'}

In [11]:
def get_genre_names(ids):
    return [genge_dict.get(i) for i in ids]
df['genres']=df['genre_ids'].apply(get_genre_names)

In [12]:
df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,genres
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,55.6183,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.700,30067,"[Drama, Crime]"
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",42.8034,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,22710,"[Drama, Crime]"
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,25.6025,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.572,13758,"[Drama, Crime]"
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,24.8810,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.567,17285,"[Drama, History, War]"
4,False,/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg,"[35, 10749]",1181678,en,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",8.5303,/9GuvODahvuFqdhuZ16aBLR4UJoP.jpg,2023-09-21,¿Quieres ser mi hijo?,False,8.558,309,"[Comedy, Romance]"

In [13]:
df['overview'][0].split()

['Imprisoned',
 'in',
 'the',
 '1940s',
 'for',
 'the',
 'double',
 'murder',
 'of',
 'his',
 'wife',
 'and',
 'her',
 'lover,',
 'upstanding',
 'banker',
 'Andy',
 'Dufresne',
 'begins',
 'a',
 'new',
 'life',
 'at',
 'the',
 'Shawshank',
 'prison,',
 'where',
 'he',
 'puts',
 'his',
 'accounting',
 'skills',
 'to',
 'work',
 'for',
 'an',
 'amoral',
 'warden.',
 'During',
 'his',
 'long',
 'stretch',
 'in',
 'prison,',
 'Dufresne',
 'comes',
 'to',
 'be',
 'admired',
 'by',
 'the',
 'other',
 'inmates',
 '--',
 'including',
 'an',
 'older',
 'prisoner',
 'named',
 'Red',
 '--',
 'for',
 'his',
 'integrity',
 'and',
 'unquenchable',
 'sense',
 'of',
 'hope.']

In [14]:
def tokenize(i):
    df['overview'][i].split()

In [15]:
df['overview'].apply(tokenize)

KeyError: 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.'

In [16]:
df['overview'][0]

'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.'

In [17]:
df['tokens']=df['overview'].apply(lambda x:x.lower().split())

In [18]:
df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,genres,tokens
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,55.6183,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.700,30067,"[Drama, Crime]","[imprisoned, in, the, 1940s, for, the, double,..."
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",42.8034,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,22710,"[Drama, Crime]","[spanning, the, years, 1945, to, 1955,, a, chr..."
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,25.6025,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.572,13758,"[Drama, Crime]","[in, the, continuing, saga, of, the, corleone,..."
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,24.8810,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.567,17285,"[Drama, History, War]","[the, true, story, of, how, businessman, oskar..."
4,False,/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg,"[35, 10749]",1181678,en,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",8.5303,/9GuvODahvuFqdhuZ16aBLR4UJoP.jpg,2023-09-21,¿Quieres ser mi hijo?,False,8.558,309,"[Comedy, Romance]","[lu,, a, conformist, woman, in, her, forties,,..."

In [19]:
df['tokens'][0]

['imprisoned',
 'in',
 'the',
 '1940s',
 'for',
 'the',
 'double',
 'murder',
 'of',
 'his',
 'wife',
 'and',
 'her',
 'lover,',
 'upstanding',
 'banker',
 'andy',
 'dufresne',
 'begins',
 'a',
 'new',
 'life',
 'at',
 'the',
 'shawshank',
 'prison,',
 'where',
 'he',
 'puts',
 'his',
 'accounting',
 'skills',
 'to',
 'work',
 'for',
 'an',
 'amoral',
 'warden.',
 'during',
 'his',
 'long',
 'stretch',
 'in',
 'prison,',
 'dufresne',
 'comes',
 'to',
 'be',
 'admired',
 'by',
 'the',
 'other',
 'inmates',
 '--',
 'including',
 'an',
 'older',
 'prisoner',
 'named',
 'red',
 '--',
 'for',
 'his',
 'integrity',
 'and',
 'unquenchable',
 'sense',
 'of',
 'hope.']

In [20]:
df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,genres,tokens
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,55.6183,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.700,30067,"[Drama, Crime]","[imprisoned, in, the, 1940s, for, the, double,..."
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",42.8034,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,22710,"[Drama, Crime]","[spanning, the, years, 1945, to, 1955,, a, chr..."
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,25.6025,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.572,13758,"[Drama, Crime]","[in, the, continuing, saga, of, the, corleone,..."
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,24.8810,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.567,17285,"[Drama, History, War]","[the, true, story, of, how, businessman, oskar..."
4,False,/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg,"[35, 10749]",1181678,en,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",8.5303,/9GuvODahvuFqdhuZ16aBLR4UJoP.jpg,2023-09-21,¿Quieres ser mi hijo?,False,8.558,309,"[Comedy, Romance]","[lu,, a, conformist, woman, in, her, forties,,..."

# another way to tokenize the text

In [21]:
import nltk
from nltk.tokenize import wordpunct_tokenize
df['tokens']=df['overview'].apply(lambda x:wordpunct_tokenize(x.lower()) if isinstance(x,str) else [])

In [45]:
df['overview'][90]

'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b'

In [43]:
def remove_special_chars(tokens):
    return [word for word in tokens if word.isalnum()]
df['tokens']=df['tokens'].apply(remove_special_chars)

In [44]:
df['tokens'][90]

['as',
 'armies',
 'mass',
 'for',
 'a',
 'final',
 'battle',
 'that',
 'will',
 'decide',
 'the',
 'fate',
 'of',
 'the',
 'world',
 'and',
 'powerful',
 'ancient',
 'forces',
 'of',
 'light',
 'and',
 'dark',
 'compete',
 'to',
 'determine',
 'the',
 'outcome',
 'one',
 'member',
 'of',
 'the',
 'fellowship',
 'of',
 'the',
 'ring',
 'is',
 'revealed',
 'as',
 'the',
 'noble',
 'heir',
 'to',
 'the',
 'throne',
 'of',
 'the',
 'kings',
 'of',
 'men',
 'yet',
 'the',
 'sole',
 'hope',
 'for',
 'triumph',
 'over',
 'evil',
 'lies',
 'with',
 'a',
 'brave',
 'hobbit',
 'frodo',
 'who',
 'accompanied',
 'by',
 'his',
 'loyal',
 'friend',
 'sam',
 'and',
 'the',
 'hideous',
 'wretched',
 'gollum',
 'ventures',
 'deep',
 'into',
 'the',
 'very',
 'dark',
 'heart',
 'of',
 'mordor',
 'on',
 'his',
 'seemingly',
 'impossible',
 'quest',
 'to',
 'destroy',
 'the',
 'ring',
 'of',
 'power']

In [46]:
df['overview'][90]

'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b'

In [47]:
df['tokens'][0]

['imprisoned',
 'in',
 'the',
 '1940s',
 'for',
 'the',
 'double',
 'murder',
 'of',
 'his',
 'wife',
 'and',
 'her',
 'lover',
 'upstanding',
 'banker',
 'andy',
 'dufresne',
 'begins',
 'a',
 'new',
 'life',
 'at',
 'the',
 'shawshank',
 'prison',
 'where',
 'he',
 'puts',
 'his',
 'accounting',
 'skills',
 'to',
 'work',
 'for',
 'an',
 'amoral',
 'warden',
 'during',
 'his',
 'long',
 'stretch',
 'in',
 'prison',
 'dufresne',
 'comes',
 'to',
 'be',
 'admired',
 'by',
 'the',
 'other',
 'inmates',
 'including',
 'an',
 'older',
 'prisoner',
 'named',
 'red',
 'for',
 'his',
 'integrity',
 'and',
 'unquenchable',
 'sense',
 'of',
 'hope']

# Note
- we can also use different approach to remove special character 
- like 1. using REGEX 2. during tokenization

In [54]:
import nltk
from nltk.corpus import stopwords
# nltk.download('stopwords')
stop_words=set(stopwords.words('english'))

In [55]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [57]:
def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]
df['tokens']=df['tokens'].apply(remove_stopwords)

In [58]:
len(df['tokens'][0])

37

In [61]:
from nltk.stem.porter import PorterStemmer

ps=PorterStemmer()

def stem_tokens(tokens):
    return [ps.stem(word) for word in tokens]
df['tokens']=df['tokens'].apply(stem_tokens)

In [62]:
df['tokens'][0]

['imprison',
 '1940',
 'doubl',
 'murder',
 'wife',
 'lover',
 'upstand',
 'banker',
 'andi',
 'dufresn',
 'begin',
 'new',
 'life',
 'shawshank',
 'prison',
 'put',
 'account',
 'skill',
 'work',
 'amor',
 'warden',
 'long',
 'stretch',
 'prison',
 'dufresn',
 'come',
 'admir',
 'inmat',
 'includ',
 'older',
 'prison',
 'name',
 'red',
 'integr',
 'unquench',
 'sens',
 'hope']

# all done in single pipeline

In [65]:
import re
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()
stop_words = set(stopwords.words('english'))

def preprocess(text):
    if isinstance(text, str):
        tokens = word_tokenize(text.lower())
        tokens = [re.sub(r'[^a-zA-Z0-9]', '', w) for w in tokens]
        tokens = [w for w in tokens if w != '']
        tokens = [w for w in tokens if w not in stop_words]
        tokens = [ps.stem(w) for w in tokens]
        return tokens
    return []

df['tokens'] = df['overview'].apply(preprocess)

In [66]:
df.head()

   adult                     backdrop_path  ...                 genres                                             tokens
0  False  /zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg  ...         [Drama, Crime]  [imprison, 1940, doubl, murder, wife, lover, u...
1  False  /tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg  ...         [Drama, Crime]  [span, year, 1945, 1955, chronicl, fiction, it...
2  False  /kGzFbGhp99zva6oZODW5atUtnqi.jpg  ...         [Drama, Crime]  [continu, saga, corleon, crime, famili, young,...
3  False  /zb6fM1CX41D9rF9hdgclu0peUmy.jpg  ...  [Drama, History, War]  [true, stori, businessman, oskar, schindler, s...
4  False  /xyWKrni8WrYzqn7ztvI5nIY0h62.jpg  ...      [Comedy, Romance]  [lu, conformist, woman, forti, learn, 15year, ...

[5 rows x 16 columns]

In [22]:
import nltk
from nltk.stem import WordNetLemmatizer

In [25]:
lemmatizer=WordNetLemmatizer()

def lemmatize_text(text):
    tokens=wordpunct_tokenize(text)
    lemmatized=[lemmatizer.lemmatize(word) for word in tokens]
    return ' '.join(lemmatized)
df['lemmatized_text']=df['overview'].apply(lemmatize_text)

In [26]:
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,genres,tokens,lemmatized_text
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,55.6183,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.700,30067,"[Drama, Crime]","[imprisoned, in, the, 1940s, for, the, double,...",Imprisoned in the 1940s for the double murder ...
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",42.8034,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,22710,"[Drama, Crime]","[spanning, the, years, 1945, to, 1955, ,, a, c...","Spanning the year 1945 to 1955 , a chronicle o..."
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,25.6025,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.572,13758,"[Drama, Crime]","[in, the, continuing, saga, of, the, corleone,...",In the continuing saga of the Corleone crime f...
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,24.8810,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.567,17285,"[Drama, History, War]","[the, true, story, of, how, businessman, oskar...",The true story of how businessman Oskar Schind...
4,False,/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg,"[35, 10749]",1181678,en,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",8.5303,/9GuvODahvuFqdhuZ16aBLR4UJoP.jpg,2023-09-21,¿Quieres ser mi hijo?,False,8.558,309,"[Comedy, Romance]","[lu, ,, a, conformist, woman, in, her, forties...","Lu , a conformist woman in her forty , learns ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9415,False,/83LbQ6xMURQYO03Ilqdr3kwLBxD.jpg,"[53, 9648]",449459,en,The Vanishing,Three lighthouse keepers on an uninhabited isl...,2.2860,/owYLROHpJWbYWEHjaEvDsnoz4Ux.jpg,2019-01-04,The Vanishing,False,5.800,778,"[Thriller, Mystery]","[three, lighthouse, keepers, on, an, uninhabit...",Three lighthouse keeper on an uninhabited isla...
9416,False,/a5o1VxHC6urCKWE620YFgYneV7j.jpg,"[27, 35]",35626,en,Return to Sleepaway Camp,When campers and staff at Camp Manabe mysterio...,1.4104,/p6V97pjGwN0fENR6mlBeUoAT73z.jpg,2008-11-04,Return to Sleepaway Camp,False,5.800,339,"[Horror, Comedy]","[when, campers, and, staff, at, camp, manabe, ...",When camper and staff at Camp Manabe mysteriou...
9417,False,/9RykqvfLhZ47ZHEmQUjyMI64zDm.jpg,"[10751, 16, 35, 12, 14]",366668,en,Playmobil: The Movie,Marla is forced to abandon her carefully struc...,1.0923,/zPQzLZnfVw9fbXyxxglyOsmQBlu.jpg,2019-06-10,Playmobil: The Movie,False,5.800,307,"[Family, Animation, Comedy, Adventure, Fantasy]","[marla, is, forced, to, abandon, her, carefull...",Marla is forced to abandon her carefully struc...
9418,False,/aIyvMthA7UGV6ix6AUUM88ZXfeU.jpg,"[14, 10751, 35, 16]",77931,en,The Smurfs 2,The evil wizard Gargamel creates a couple of m...,4.6767,/tmjvgbEH4BKYFfHmWXjXrHgi8wT.jpg,2013-07-30,The Smurfs 2,False,5.800,2352,"[Fantasy, Family, Comedy, Animation]","[the, evil, wizard, gargamel, creates, a, coup...",The evil wizard Gargamel creates a couple of m...
9419,False,/bMVhgI3jFvsoDeCseRsaxYR1nUA.jpg,"[28, 35, 878]",10679,en,Iron Sky,"In the last moments of World War II, a secret ...",3.9264,/hVDJM29BSbET4FzI24xLuWSmDUR.jpg,2012-04-04,Iron Sky,False,5.750,1751,"[Action, Comedy, Science Fiction]","[in, the, last, moments, of, world, war, ii, ,...","In the last moment of World War II , a secret ..."

In [28]:
print(df['tokens'][0])
print(df['lemmatized_text'][0])

['imprisoned', 'in', 'the', '1940s', 'for', 'the', 'double', 'murder', 'of', 'his', 'wife', 'and', 'her', 'lover', ',', 'upstanding', 'banker', 'andy', 'dufresne', 'begins', 'a', 'new', 'life', 'at', 'the', 'shawshank', 'prison', ',', 'where', 'he', 'puts', 'his', 'accounting', 'skills', 'to', 'work', 'for', 'an', 'amoral', 'warden', '.', 'during', 'his', 'long', 'stretch', 'in', 'prison', ',', 'dufresne', 'comes', 'to', 'be', 'admired', 'by', 'the', 'other', 'inmates', '--', 'including', 'an', 'older', 'prisoner', 'named', 'red', '--', 'for', 'his', 'integrity', 'and', 'unquenchable', 'sense', 'of', 'hope', '.']
Imprisoned in the 1940s for the double murder of his wife and her lover , upstanding banker Andy Dufresne begin a new life at the Shawshank prison , where he put his accounting skill to work for an amoral warden . During his long stretch in prison , Dufresne come to be admired by the other inmate -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope .

In [29]:
df1 = pd.DataFrame({
    'text': [
        "I am running and feeling better",
        "She studies very hard",
        "He went to the market"
    ]
})

In [30]:
df1['text'].apply(lemmatize_text)

0    I am running and feeling better
1                She study very hard
2              He went to the market
Name: text, dtype: str

In [31]:
lemmatizer = WordNetLemmatizer()

words = ["running", "better", "studies", "went"]

for word in words:
    print(word, "->", lemmatizer.lemmatize(word))

running -> running
better -> better
studies -> study
went -> went

In [32]:
lemmatizer.lemmatize("running", pos='v')   # run
lemmatizer.lemmatize("better", pos='a')    # good
lemmatizer.lemmatize("went", pos='v')      # go

'go'

In [33]:
lemmatizer.lemmatize("better", pos='a')

'good'

In [34]:
lemmatizer.lemmatize("running", pos='v')

'run'

In [35]:
lemmatizer.lemmatize('he',pos='n')

'he'

In [36]:
sentence = "I am running and feeling better"

tokens = sentence.split()

lemmatized = [lemmatizer.lemmatize(word, pos='v') for word in tokens]

print(lemmatized)

['I', 'be', 'run', 'and', 'feel', 'better']