# text-representation

In [1]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "IMDB Dataset.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "lakshmi25npathi/imdb-dataset-of-50k-movie-reviews",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

C:\Users\USER\AppData\Local\Temp\ipykernel_6844\3310047898.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

First 5 records:                                               review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [2]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

### removing the html tags, special chracters and stopwords

In [3]:
import pandas as pd

In [6]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [8]:
stop_words=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()

In [10]:
def clean_text(text):
    # 1. remove html tags
    text=re.sub(r'<.*?>','',text) 
    
    # 2.lowercase
    text=text.lower()

    # 3. remove special characters & numbers
    text=re.sub(r'[^a-zA-Z\s]',' ',text)

    # 4. Tokenization
    tokens=word_tokenize(text)

    # 5. Remove stopwords
    tokens=[word for word in tokens if word not in stop_words]

    # 6. Lemmatization
    tokens=[lemmatizer.lemmatize(word,pos='v') for word in tokens]

    

    return " ".join(tokens)

In [11]:
df['clean_review']=df['review'].apply(clean_text)

In [12]:
df.head()

,review,sentiment,clean_review
0,One of the other reviewers has mentioned that ...,positive,one reviewers mention watch oz episode hook ri...
1,A wonderful little production. <br /><br />The...,positive,wonderful little production film technique una...
2,I thought this was a wonderful way to spend ti...,positive,think wonderful way spend time hot summer week...
3,Basically there's a family where a little boy ...,negative,basically family little boy jake think zombie ...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter mattei love time money visually stun fi...

In [13]:
corpus=" ".join(df['clean_review'])
corpus[0:10]

'one review'

In [14]:
len(corpus)# it also count the spaces

38975682

In [15]:
tokens=corpus.split()

In [16]:
len(tokens)# it doesn't count spaces

5905999

In [18]:
len(corpus)/len(tokens)

6.897625448294184

### vocabulary (finding unique word)

In [18]:
vocabulary=set(tokens)

In [19]:
len(vocabulary)

88514

## Tokenization

In [21]:
from nltk.tokenize import word_tokenize
import nltk
df['word_tokenize']=df['review'].apply(word_tokenize)

In [22]:
df.head()

,review,sentiment,clean_review,word_tokenize
0,One of the other reviewers has mentioned that ...,positive,one reviewers mention watch oz episode hook ri...,"[One, of, the, other, reviewers, has, mentione..."
1,A wonderful little production. <br /><br />The...,positive,wonderful little production film technique una...,"[A, wonderful, little, production, ., <, br, /..."
2,I thought this was a wonderful way to spend ti...,positive,think wonderful way spend time hot summer week...,"[I, thought, this, was, a, wonderful, way, to,..."
3,Basically there's a family where a little boy ...,negative,basically family little boy jake think zombie ...,"[Basically, there, 's, a, family, where, a, li..."
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter mattei love time money visually stun fi...,"[Petter, Mattei, 's, ``, Love, in, the, Time, ..."

In [26]:
df['word_tokenize']=df['clean_review'].apply(word_tokenize)

In [31]:
from nltk.tokenize import sent_tokenize
df['sent_tokenize']=df['review'].apply(sent_tokenize)

In [32]:
df.head()

,review,sentiment,clean_review,word_tokenize,sent_tokenize
0,One of the other reviewers has mentioned that ...,positive,one reviewers mention watch oz episode hook ri...,"[one, reviewers, mention, watch, oz, episode, ...",[One of the other reviewers has mentioned that...
1,A wonderful little production. <br /><br />The...,positive,wonderful little production film technique una...,"[wonderful, little, production, film, techniqu...","[A wonderful little production., <br /><br />T..."
2,I thought this was a wonderful way to spend ti...,positive,think wonderful way spend time hot summer week...,"[think, wonderful, way, spend, time, hot, summ...",[I thought this was a wonderful way to spend t...
3,Basically there's a family where a little boy ...,negative,basically family little boy jake think zombie ...,"[basically, family, little, boy, jake, think, ...",[Basically there's a family where a little boy...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter mattei love time money visually stun fi...,"[petter, mattei, love, time, money, visually, ...","[Petter Mattei's ""Love in the Time of Money"" i..."

In [33]:
len(df['sent_tokenize'][0])

10

# text preprocessing
### Grams
- unigram
- bigram
- trigram
- ngram

In [35]:
from nltk.util import bigrams
def generate_bigrams(text):
    return [' '.join(bg) for bg in  bigrams(text)]
df['bigram']=df['word_tokenize'].apply(generate_bigrams)
df.head()

,review,sentiment,clean_review,word_tokenize,sent_tokenize,bigram
0,One of the other reviewers has mentioned that ...,positive,one reviewers mention watch oz episode hook ri...,"[one, reviewers, mention, watch, oz, episode, ...",[One of the other reviewers has mentioned that...,"[one reviewers, reviewers mention, mention wat..."
1,A wonderful little production. <br /><br />The...,positive,wonderful little production film technique una...,"[wonderful, little, production, film, techniqu...","[A wonderful little production., <br /><br />T...","[wonderful little, little production, producti..."
2,I thought this was a wonderful way to spend ti...,positive,think wonderful way spend time hot summer week...,"[think, wonderful, way, spend, time, hot, summ...",[I thought this was a wonderful way to spend t...,"[think wonderful, wonderful way, way spend, sp..."
3,Basically there's a family where a little boy ...,negative,basically family little boy jake think zombie ...,"[basically, family, little, boy, jake, think, ...",[Basically there's a family where a little boy...,"[basically family, family little, little boy, ..."
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter mattei love time money visually stun fi...,"[petter, mattei, love, time, money, visually, ...","[Petter Mattei's ""Love in the Time of Money"" i...","[petter mattei, mattei love, love time, time m..."

In [38]:
len(df['bigram'][0])

161

In [39]:
from nltk.util import trigrams
def generate_trigrams(text):
    return [' '.join(bg) for bg in  trigrams(text)]
df['trigram']=df['word_tokenize'].apply(generate_trigrams)
df.head()

,review,sentiment,clean_review,word_tokenize,sent_tokenize,bigram,trigram
0,One of the other reviewers has mentioned that ...,positive,one reviewers mention watch oz episode hook ri...,"[one, reviewers, mention, watch, oz, episode, ...",[One of the other reviewers has mentioned that...,"[one reviewers, reviewers mention, mention wat...","[one reviewers mention, reviewers mention watc..."
1,A wonderful little production. <br /><br />The...,positive,wonderful little production film technique una...,"[wonderful, little, production, film, techniqu...","[A wonderful little production., <br /><br />T...","[wonderful little, little production, producti...","[wonderful little production, little productio..."
2,I thought this was a wonderful way to spend ti...,positive,think wonderful way spend time hot summer week...,"[think, wonderful, way, spend, time, hot, summ...",[I thought this was a wonderful way to spend t...,"[think wonderful, wonderful way, way spend, sp...","[think wonderful way, wonderful way spend, way..."
3,Basically there's a family where a little boy ...,negative,basically family little boy jake think zombie ...,"[basically, family, little, boy, jake, think, ...",[Basically there's a family where a little boy...,"[basically family, family little, little boy, ...","[basically family little, family little boy, l..."
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter mattei love time money visually stun fi...,"[petter, mattei, love, time, money, visually, ...","[Petter Mattei's ""Love in the Time of Money"" i...","[petter mattei, mattei love, love time, time m...","[petter mattei love, mattei love time, love ti..."

In [41]:
len(df['trigram'][0])

160

In [42]:
from nltk.util import ngrams
def generate_ngrams(text):
    return [' '.join(bg) for bg in  ngrams(text,10)]
df['ngram']=df['word_tokenize'].apply(generate_ngrams)
df.head()

,review,sentiment,clean_review,word_tokenize,sent_tokenize,bigram,trigram,ngram
0,One of the other reviewers has mentioned that ...,positive,one reviewers mention watch oz episode hook ri...,"[one, reviewers, mention, watch, oz, episode, ...",[One of the other reviewers has mentioned that...,"[one reviewers, reviewers mention, mention wat...","[one reviewers mention, reviewers mention watc...",[one reviewers mention watch oz episode hook r...
1,A wonderful little production. <br /><br />The...,positive,wonderful little production film technique una...,"[wonderful, little, production, film, techniqu...","[A wonderful little production., <br /><br />T...","[wonderful little, little production, producti...","[wonderful little production, little productio...",[wonderful little production film technique un...
2,I thought this was a wonderful way to spend ti...,positive,think wonderful way spend time hot summer week...,"[think, wonderful, way, spend, time, hot, summ...",[I thought this was a wonderful way to spend t...,"[think wonderful, wonderful way, way spend, sp...","[think wonderful way, wonderful way spend, way...",[think wonderful way spend time hot summer wee...
3,Basically there's a family where a little boy ...,negative,basically family little boy jake think zombie ...,"[basically, family, little, boy, jake, think, ...",[Basically there's a family where a little boy...,"[basically family, family little, little boy, ...","[basically family little, family little boy, l...",[basically family little boy jake think zombie...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter mattei love time money visually stun fi...,"[petter, mattei, love, time, money, visually, ...","[Petter Mattei's ""Love in the Time of Money"" i...","[petter mattei, mattei love, love time, time m...","[petter mattei love, mattei love time, love ti...",[petter mattei love time money visually stun f...

In [45]:
len(df['ngram'][0])

153

In [47]:
df['clean_review']

(50000,)

# OHE(One hot Encoding)
- 👉 In NLP, OHE is used differently:

- Instead of categories → we encode words

### But in NLP we DON'T use OHE directly ❗

- 👉 Because:

- Huge vocabulary → too many columns
- Sparse matrix (inefficient)

### 🔹 Instead use:
- Bag of Words
- TF-IDF

- (These are optimized versions of OHE for text 💯)

In [56]:
from sklearn.preprocessing import OneHotEncoder


ohe=OneHotEncoder(sparse_output=False)
encoded=ohe.fit_transform(df[['clean_review']])
encoded_df=pd.DataFrame(encoded,columns=ohe.get_feature_names_out())
df_final=pd.concat([df,encoded_df],axis=1)

MemoryError: Unable to allocate 18.5 GiB for an array with shape (50000, 49574) and data type float64

In [50]:
words=df['word_tokenize']

(50000,)

# Bag of Words

In [70]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000)
X=cv.fit_transform(df['clean_review'])

In [71]:
X.shape

(50000, 5000)

In [72]:
vocab=cv.get_feature_names_out()

In [74]:
vocab[1000:1090]

array(['crack', 'craft', 'craig', 'crap', 'crappy', 'crash', 'craven',
       'crawford', 'crawl', 'craze', 'crazy', 'cream', 'create',
       'creation', 'creative', 'creativity', 'creator', 'creators',
       'creature', 'creatures', 'credibility', 'credible', 'credit',
       'creep', 'creepy', 'crew', 'crime', 'crimes', 'criminal',
       'criminals', 'cringe', 'cripple', 'crisis', 'crisp', 'critic',
       'critical', 'criticism', 'criticize', 'critics', 'critique',
       'critters', 'crocodile', 'crook', 'cross', 'crowd', 'crown',
       'crucial', 'crude', 'cruel', 'cruelty', 'cruise', 'crush', 'cry',
       'crystal', 'cuba', 'cube', 'cue', 'cult', 'cultural', 'culture',
       'cup', 'cure', 'curiosity', 'curious', 'curly', 'current',
       'currently', 'curse', 'curtis', 'cusack', 'cushing', 'custer',
       'cut', 'cute', 'cycle', 'cynical', 'da', 'dad', 'daddy', 'daily',
       'dallas', 'dalton', 'damage', 'dame', 'damme', 'damn', 'damon',
       'dan', 'dana', 'dance'], dtype=object)

In [67]:
vocab[0]

'aa'

In [76]:
bow_df = pd.DataFrame(X.toarray(), columns=vocab)

bow_df.head()

,aaron,abandon,abc,abilities,ability,able,abound,abrupt,absence,absent,...,young,younger,youngest,youth,youtube,zero,zombie,zombies,zone,zoom
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [77]:
word_counts = bow_df.sum(axis=0)

print(word_counts.sort_values(ascending=False).head(10))

film         95850
movie        87937
one          53585
make         46129
like         44297
see          41611
get          35729
time         31905
good         29737
character    28344
dtype: int64

In [79]:
bow_df['get'].sum()

np.int64(35729)

In [80]:
from sklearn.feature_extraction.text import CountVectorizer

# Bigram
cv_bigram = CountVectorizer(ngram_range=(2,2), max_features=5000)

X_bigram = cv_bigram.fit_transform(df['clean_review'])

bigram_vocab = cv_bigram.get_feature_names_out()

print("Bigram Vocabulary Size:", len(bigram_vocab))

Bigram Vocabulary Size: 5000

In [81]:
# Trigram
cv_trigram = CountVectorizer(ngram_range=(3,3), max_features=5000)

X_trigram = cv_trigram.fit_transform(df['clean_review'])

trigram_vocab = cv_trigram.get_feature_names_out()

print("Trigram Vocabulary Size:", len(trigram_vocab))

Trigram Vocabulary Size: 5000

In [82]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X=tfidf.fit_transform(df['clean_review'])

In [84]:
vocab=tfidf.get_feature_names_out()
len(vocab)

88496

# get idf scores

In [87]:
idf_scores=tfidf.idf_

# combine word +idf
idf_dict=dict(zip(vocab,idf_scores))

# print top 10
for word,score in list(idf_dict.items())[:10]:
    print(word,':',score)

aa : 9.180740954595027
aaa : 9.25484892674875
aaaaaaaaaaaahhhhhhhhhhhhhh : 11.12665110365034
aaaaaaaargh : 11.12665110365034
aaaaaaah : 11.12665110365034
aaaaaaahhhhhhggg : 11.12665110365034
aaaaagh : 11.12665110365034
aaaaah : 10.721185995542177
aaaaahhhh : 11.12665110365034
aaaaargh : 11.12665110365034