In [1]:
import numpy as np
import pandas as pd

In [2]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "IMDB Dataset.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "lakshmi25npathi/imdb-dataset-of-50k-movie-reviews",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

df.head()

C:\Users\USER\AppData\Local\Temp\ipykernel_16404\3431149111.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
df.shape

(50000, 2)

In [4]:
df.drop_duplicates(inplace=True)

In [5]:
df.shape

(49582, 2)

In [6]:
import re
def remove_tags(raw_text):
    cleaned_text=re.sub(re.compile('<.*?>'),'',raw_text)
    return cleaned_text
df['review']=df['review'].apply(remove_tags)

In [7]:
df.head(2)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. The filming tec...  positive

In [8]:
df['review']=df['review'].apply(lambda x:x.lower())

In [9]:
df.head(1)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive

In [10]:
from nltk.corpus import stopwords

sw_list=stopwords.words('english')
df['review']=df['review'].apply(lambda x:[item for item in x.split() if item not in sw_list]).apply(lambda x:' '.join(x))

In [11]:
df.head(2)

                                              review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production. filming technique...  positive

In [12]:
import gensim

In [13]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [14]:
story=[]

for doc in df['review']:
    raw_sent=sent_tokenize(doc)

    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [15]:
story[0:100]

[['one', 'reviewers', 'mentioned', 'watching', 'oz', 'episode', 'hooked'],
 ['right',
  'exactly',
  'happened',
  'me',
  'the',
  'first',
  'thing',
  'struck',
  'oz',
  'brutality',
  'unflinching',
  'scenes',
  'violence',
  'set',
  'right',
  'word',
  'go'],
 ['trust', 'me', 'show', 'faint', 'hearted', 'timid'],
 ['show', 'pulls', 'punches', 'regards', 'drugs', 'sex', 'violence'],
 ['hardcore',
  'classic',
  'use',
  'word',
  'it',
  'called',
  'oz',
  'nickname',
  'given',
  'oswald',
  'maximum',
  'security',
  'state',
  'penitentary'],
 ['focuses',
  'mainly',
  'emerald',
  'city',
  'experimental',
  'section',
  'prison',
  'cells',
  'glass',
  'fronts',
  'face',
  'inwards',
  'privacy',
  'high',
  'agenda'],
 ['em',
  'city',
  'home',
  'many',
  'aryans',
  'muslims',
  'gangstas',
  'latinos',
  'christians',
  'italians',
  'irish',
  'more',
  'so',
  'scuffles',
  'death',
  'stares',
  'dodgy',
  'dealings',
  'shady',
  'agreements',
  'never',
  'far',
  'away',
  'would',
  'say',
  'main',
  'appeal',
  'show',
  'due',
  'fact',
  'goes',
  'shows',
  'dare'],
 ['forget',
  'pretty',
  'pictures',
  'painted',
  'mainstream',
  'audiences',
  'forget',
  'charm',
  'forget',
  'romance',
  'oz',
  'mess',
  'around'],
 ['first',
  'episode',
  'ever',
  'saw',
  'struck',
  'nasty',
  'surreal',
  'say',
  'ready',
  'it',
  'watched',
  'more',
  'developed',
  'taste',
  'oz',
  'got',
  'accustomed',
  'high',
  'levels',
  'graphic',
  'violence'],
 ['violence',
  'injustice',
  'crooked',
  'guards',
  'who',
  'll',
  'sold',
  'nickel',
  'inmates',
  'who',
  'll',
  'kill',
  'order',
  'get',
  'away',
  'it',
  'well',
  'mannered',
  'middle',
  'class',
  'inmates',
  'turned',
  'prison',
  'bitches',
  'due',
  'lack',
  'street',
  'skills',
  'prison',
  'experience',
  'watching',
  'oz',
  'may',
  'become',
  'comfortable',
  'uncomfortable',
  'viewing',
  'thats',
  'get',
  'touch',
  'darker',
  'side'],
 ['wonderful', 'little', 'production'],
 ['filming',
  'technique',
  'unassuming',
  'old',
  'time',
  'bbc',
  'fashion',
  'gives',
  'comforting',
  'sometimes',
  'discomforting',
  'sense',
  'realism',
  'entire',
  'piece'],
 ['actors',
  'extremely',
  'well',
  'chosen',
  'michael',
  'sheen',
  'has',
  'got',
  'polari',
  'voices',
  'pat',
  'too'],
 ['truly',
  'see',
  'seamless',
  'editing',
  'guided',
  'references',
  'williams',
  'diary',
  'entries',
  'well',
  'worth',
  'watching',
  'terrificly',
  'written',
  'performed',
  'piece'],
 ['masterful', 'production', 'one', 'great', 'master', 'comedy', 'life'],
 ['realism',
  'really',
  'comes',
  'home',
  'little',
  'things',
  'fantasy',
  'guard',
  'which',
  'rather',
  'use',
  'traditional',
  'dream',
  'techniques',
  'remains',
  'solid',
  'disappears'],
 ['plays',
  'knowledge',
  'senses',
  'particularly',
  'scenes',
  'concerning',
  'orton',
  'halliwell',
  'sets',
  'particularly',
  'flat',
  'halliwell',
  'murals',
  'decorating',
  'every',
  'surface',
  'terribly',
  'well',
  'done'],
 ['thought',
  'wonderful',
  'way',
  'spend',
  'time',
  'hot',
  'summer',
  'weekend',
  'sitting',
  'air',
  'conditioned',
  'theater',
  'watching',
  'light',
  'hearted',
  'comedy'],
 ['plot',
  'simplistic',
  'dialogue',
  'witty',
  'characters',
  'likable',
  'even',
  'well',
  'bread',
  'suspected',
  'serial',
  'killer'],
 ['may',
  'disappointed',
  'realize',
  'match',
  'point',
  'risk',
  'addiction',
  'thought',
  'proof',
  'woody',
  'allen',
  'still',
  'fully',
  'control',
  'style',
  'many',
  'us',
  'grown',
  'love',
  'this',
  'laughed',
  'one',
  'woody',
  'comedies',
  'years',
  'dare',
  'say',
  'decade'],
 ['never',
  'impressed',
  'scarlet',
  'johanson',
  'managed',
  'tone',
  'sexy',
  'image',
  'jumped',
  'right',
  'average',
  'spirited',
  'young',
  'woman',
  'this',
  'may',
  'crown',
  'jewel',
  'career',
  'wittier',
  'devil',
  'wears',
  'prada',
  'interesting',
  'superman',
  'great',
  'comedy',
  'go',
  'see',
  'friends'],
 ['basically',
  'there',
  'family',
  'little',
  'boy',
  'jake',
  'thinks',
  'there',
  'zombie',
  'closet',
  'parents',
  'fighting',
  'time',
  'this',
  'movie',
  'slower',
  'soap',
  'opera',
  'suddenly',
  'jake',
  'decides',
  'become',
  'rambo',
  'kill',
  'zombie',
  'ok',
  'first',
  'going',
  'make',
  'film',
  'must',
  'decide',
  'thriller',
  'drama'],
 ['drama', 'movie', 'watchable'],
 ['parents', 'divorcing', 'arguing', 'like', 'real', 'life'],
 ['jake', 'closet', 'totally', 'ruins', 'film'],
 ['expected',
  'see',
  'boogeyman',
  'similar',
  'movie',
  'instead',
  'watched',
  'drama',
  'meaningless',
  'thriller',
  'spots',
  'well',
  'playing',
  'parents',
  'descent',
  'dialogs'],
 ['shots', 'jake', 'ignore', 'them'],
 ['petter',
  'mattei',
  'love',
  'time',
  'money',
  'visually',
  'stunning',
  'film',
  'watch'],
 ['mr', 'mattei', 'offers', 'us', 'vivid', 'portrait', 'human', 'relations'],
 ['movie',
  'seems',
  'telling',
  'us',
  'money',
  'power',
  'success',
  'people',
  'different',
  'situations',
  'encounter'],
 ['variation',
  'arthur',
  'schnitzler',
  'play',
  'theme',
  'director',
  'transfers',
  'action',
  'present',
  'time',
  'new',
  'york',
  'different',
  'characters',
  'meet',
  'connect'],
 ['one',
  'connected',
  'one',
  'way',
  'another',
  'next',
  'person',
  'one',
  'seems',
  'know',
  'previous',
  'point',
  'contact'],
 ['stylishly', 'film', 'sophisticated', 'luxurious', 'look'],
 ['taken',
  'see',
  'people',
  'live',
  'world',
  'live',
  'habitat',
  'the',
  'thing',
  'one',
  'gets',
  'souls',
  'picture',
  'different',
  'stages',
  'loneliness',
  'one',
  'inhabits'],
 ['big',
  'city',
  'exactly',
  'best',
  'place',
  'human',
  'relations',
  'find',
  'sincere',
  'fulfillment',
  'one',
  'discerns',
  'case',
  'people',
  'encounter',
  'the',
  'acting',
  'good',
  'mr',
  'mattei',
  'direction'],
 ['steve',
  'buscemi',
  'rosario',
  'dawson',
  'carol',
  'kane',
  'michael',
  'imperioli',
  'adrian',
  'grenier',
  'rest',
  'talented',
  'cast',
  'make',
  'characters',
  'come',
  'alive',
  'we',
  'wish',
  'mr',
  'mattei',
  'good',
  'luck',
  'await',
  'anxiously',
  'next',
  'work'],
 ['probably',
  'all',
  'time',
  'favorite',
  'movie',
  'story',
  'selflessness',
  'sacrifice',
  'dedication',
  'noble',
  'cause',
  'preachy',
  'boring'],
 ['never', 'gets', 'old', 'despite', 'seen', 'times', 'last', 'years'],
 ['paul',
  'lukas',
  'performance',
  'brings',
  'tears',
  'eyes',
  'bette',
  'davis',
  'one',
  'truly',
  'sympathetic',
  'roles',
  'delight'],
 ['kids',
  'are',
  'grandma',
  'says',
  'like',
  'dressed',
  'up',
  'midgets',
  'children',
  'makes',
  'fun',
  'watch'],
 ['mother',
  'slow',
  'awakening',
  'what',
  'happening',
  'world',
  'roof',
  'believable',
  'startling'],
 ['dozen', 'thumbs', 'up', 'movie'],
 ['sure',
  'would',
  'like',
  'see',
  'resurrection',
  'dated',
  'seahunt',
  'series',
  'tech',
  'today',
  'would',
  'bring',
  'back',
  'kid',
  'excitement',
  'me',
  'grew',
  'black',
  'white',
  'tv',
  'seahunt',
  'gunsmoke',
  'hero',
  'every',
  'week',
  'you',
  'vote',
  'comeback',
  'new',
  'sea',
  'hunt',
  'we',
  'need',
  'change',
  'pace',
  'tv',
  'would',
  'work',
  'world',
  'water',
  'adventure',
  'oh',
  'way',
  'thank',
  'outlet',
  'like',
  'view',
  'many',
  'viewpoints',
  'tv',
  'many',
  'movies',
  'so',
  'ole',
  'way',
  'believe',
  'got',
  'wanna',
  'say',
  'would',
  'nice',
  'read',
  'plus',
  'points',
  'sea',
  'hunt',
  'if',
  'rhymes',
  'would',
  'lines',
  'would',
  'let',
  'submit',
  'or',
  'leave',
  'doubt',
  'quit',
  'if',
  'must',
  'go',
  'lets',
  'it'],
 ['show', 'amazing', 'fresh', 'innovative', 'idea', 'first', 'aired'],
 ['first', 'years', 'brilliant', 'things', 'dropped', 'that'],
 ['show',
  'really',
  'funny',
  'anymore',
  'continued',
  'decline',
  'complete',
  'waste',
  'time',
  'today',
  'it',
  'truly',
  'disgraceful',
  'far',
  'show',
  'fallen'],
 ['writing',
  'painfully',
  'bad',
  'performances',
  'almost',
  'bad',
  'mildly',
  'entertaining',
  'respite',
  'guest',
  'hosts',
  'show',
  'probably',
  'still',
  'air'],
 ['find',
  'hard',
  'believe',
  'creator',
  'hand',
  'selected',
  'original',
  'cast',
  'also',
  'chose',
  'band',
  'hacks',
  'followed'],
 ['one', 'recognize', 'brilliance', 'see', 'fit', 'replace', 'mediocrity'],
 ['felt',
  'must',
  'give',
  'stars',
  'respect',
  'original',
  'cast',
  'made',
  'show',
  'huge',
  'success'],
 ['now', 'show', 'awful'],
 ['can', 'believe', 'still', 'air'],
 ['encouraged',
  'positive',
  'comments',
  'film',
  'looking',
  'forward',
  'watching',
  'film'],
 ['bad', 'mistake'],
 ['seen',
  'films',
  'truly',
  'one',
  'worst',
  'awful',
  'almost',
  'every',
  'way',
  'editing',
  'pacing',
  'storyline',
  'acting',
  'soundtrack',
  'the',
  'film',
  'song',
  'lame',
  'country',
  'tune',
  'played',
  'less',
  'four',
  'times'],
 ['film', 'looks', 'cheap', 'nasty', 'boring', 'extreme'],
 ['rarely', 'happy', 'see', 'end', 'credits', 'film'],
 ['thing',
  'prevents',
  'giving',
  'score',
  'harvey',
  'keitel',
  'far',
  'best',
  'performance',
  'least',
  'seems',
  'making',
  'bit',
  'effort'],
 ['one', 'keitel', 'obsessives', 'only'],
 ['like', 'original', 'gut', 'wrenching', 'laughter', 'like', 'movie'],
 ['young',
  'old',
  'love',
  'movie',
  'hell',
  'even',
  'mom',
  'liked',
  'it',
  'great',
  'camp'],
 [],
 ['phil',
  'alien',
  'one',
  'quirky',
  'films',
  'humour',
  'based',
  'around',
  'oddness',
  'everything',
  'rather',
  'actual',
  'punchlines',
  'at',
  'first',
  'odd',
  'pretty',
  'funny',
  'movie',
  'progressed',
  'find',
  'jokes',
  'oddness',
  'funny',
  'anymore',
  'its',
  'low',
  'budget',
  'film',
  'thats',
  'never',
  'problem',
  'itself',
  'pretty',
  'interesting',
  'characters',
  'eventually',
  'lost',
  'interest',
  'imagine',
  'film',
  'would',
  'appeal',
  'stoner',
  'currently',
  'partaking',
  'for',
  'something',
  'similar',
  'better',
  'try',
  'brother',
  'another',
  'planet'],
 ['saw', 'movie', 'came', 'out'],
 ['recall',
  'scariest',
  'scene',
  'big',
  'bird',
  'eating',
  'men',
  'dangling',
  'helplessly',
  'parachutes',
  'right',
  'air'],
 ['horror'],
 ['horror',
  'as',
  'young',
  'kid',
  'going',
  'cheesy',
  'films',
  'saturday',
  'afternoons',
  'still',
  'tired',
  'formula',
  'monster',
  'type',
  'movies',
  'usually',
  'included',
  'hero',
  'beautiful',
  'woman',
  'might',
  'daughter',
  'professor',
  'happy',
  'resolution',
  'monster',
  'died',
  'end'],
 ['care', 'much', 'romantic', 'angle', 'year', 'old', 'predictable', 'plots'],
 ['love',
  'unintentional',
  'humor',
  'but',
  'year',
  'later',
  'saw',
  'psycho',
  'came',
  'loved',
  'star',
  'janet',
  'leigh',
  'bumped',
  'early',
  'film'],
 ['sat', 'took', 'notice', 'point'],
 ['since',
  'screenwriters',
  'making',
  'story',
  'make',
  'scary',
  'possible',
  'well',
  'worn',
  'formula'],
 ['rules'],
 ['im', 'big', 'fan', 'boll', 'work', 'many', 'are'],
 ['enjoyed', 'movie', 'postal', 'maybe', 'im', 'one'],
 ['boll',
  'apparently',
  'bought',
  'rights',
  'use',
  'far',
  'cry',
  'long',
  'ago',
  'even',
  'game',
  'even',
  'finsished'],
 ['people',
  'enjoyed',
  'killing',
  'mercs',
  'infiltrating',
  'secret',
  'research',
  'labs',
  'located',
  'tropical',
  'island',
  'warned',
  'far',
  'cry',
  'something',
  'mr',
  'boll',
  'schemed',
  'together',
  'along',
  'legion',
  'schmucks',
  'feeling',
  'loneley',
  'set',
  'mr',
  'boll',
  'invites',
  'three',
  'countrymen',
  'play',
  'with'],
 ['players',
  'go',
  'names',
  'til',
  'schweiger',
  'udo',
  'kier',
  'ralf',
  'moeller',
  'three',
  'names',
  'actually',
  'made',
  'selfs',
  'pretty',
  'big',
  'movie',
  'biz'],
 ['tale',
  'goes',
  'like',
  'this',
  'jack',
  'carver',
  'played',
  'til',
  'schweiger',
  'yes',
  'carver',
  'german',
  'hail',
  'bratwurst',
  'eating',
  'dudes'],
 ['however',
  'find',
  'tils',
  'acting',
  'movie',
  'pretty',
  'badass',
  'people',
  'complained',
  'really',
  'staying',
  'true',
  'whole',
  'carver',
  'agenda',
  'saw',
  'carver',
  'first',
  'person',
  'perspective',
  'really',
  'know',
  'looked',
  'like',
  'kicking',
  'however',
  'storyline',
  'film',
  'beyond',
  'demented'],
 ['see',
  'evil',
  'mad',
  'scientist',
  'dr',
  'krieger',
  'played',
  'udo',
  'kier',
  'making',
  'genetically',
  'mutated',
  'soldiers',
  'gms',
  'called'],
 ['performing',
  'top',
  'secret',
  'research',
  'island',
  'reminds',
  'spoiler',
  'vancouver',
  'reason'],
 ['thats', 'right', 'palm', 'trees', 'here'],
 ['instead', 'got', 'nice', 'rich', 'lumberjack', 'woods'],
 ['even',
  'gone',
  'far',
  'started',
  'cry',
  'mehehe',
  'cannot',
  'go',
  'more',
  'wanna',
  'stay',
  'true',
  'bolls',
  'shenanigans',
  'go',
  'see',
  'movie',
  'disappointed',
  'delivers',
  'true',
  'boll',
  'experience',
  'meaning',
  'suck',
  'there',
  'things',
  'worth',
  'mentioning',
  'would',
  'imply',
  'boll',
  'good',
  'work',
  'areas',
  'film',
  'nice',
  'boat',
  'fighting',
  'scenes'],
 ['whole',
  'cromed',
  'albino',
  'gms',
  'squad',
  'enters',
  'scene',
  'everything',
  'makes',
  'laugh',
  'movie',
  'far',
  'cry',
  'reeks',
  'scheisse',
  'that',
  'poop',
  'simpletons',
  'fa',
  'wanna',
  'take',
  'wiff',
  'go',
  'ahead',
  'btw',
  'carver',
  'gets',
  'annoying',
  'sidekick',
  'makes',
  'wanna',
  'shoot',
  'first',
  'three',
  'minutes',
  'screen'],
 ['cast',
  'played',
  'shakespeare',
  'shakespeare',
  'lost',
  'appreciate',
  'trying',
  'bring',
  'shakespeare',
  'masses',
  'ruin',
  'something',
  'good',
  'is',
  'the',
  'scottish',
  'play',
  'favorite',
  'shakespeare'],
 ['know'],
 ['know',
  'certain',
  'rev',
  'bowdler',
  'hence',
  'bowdlerization',
  'tried',
  'something',
  'similar',
  'victorian',
  'era',
  'in',
  'words',
  'cannot',
  'improve',
  'perfection',
  'write',
  'write',
  'least',
  'ten',
  'lines',
  'text',
  'and',
  'english',
  'composition',
  'never',
  'forte',
  'keep',
  'going',
  'say',
  'movie',
  'saying',
  'goes',
  'cut',
  'it'],
 ['fantastic', 'movie', 'three', 'prisoners', 'become', 'famous'],
 ['one', 'actors', 'george', 'clooney', 'fan', 'roll', 'bad'],
 ['another',
  'good',
  'thing',
  'movie',
  'soundtrack',
  'the',
  'man',
  'constant',
  'sorrow'],
 ['recommand', 'movie', 'everybody'],
 ['greetings', 'bart'],
 ['kind',
  'drawn',
  'erotic',
  'scenes',
  'realize',
  'one',
  'amateurish',
  'unbelievable',
  'bits',
  'film',
  'ever',
  'seen'],
 ['sort', 'like', 'high', 'school', 'film', 'project'],
 ['rosanna', 'arquette', 'thinking'],
 ['stock', 'characters', 'bizarre', 'supposed', 'midwest', 'town'],
 ['pretty', 'hard', 'get', 'involved', 'one'],
 ['lessons',
  'learned',
  'it',
  'brilliant',
  'insights',
  'stilted',
  'quite',
  'ridiculous',
  'but',
  'lots',
  'skin',
  'intrigues',
  'you',
  'videotaped',
  'nonsense',
  'what',
  'bisexual',
  'relationship',
  'nowhere',
  'heterosexual',
  'encounters'],
 ['absurd', 'dance', 'everybody', 'playing', 'stereotyped', 'roles']]

In [16]:
len(story)

528620

In [17]:
model=gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [18]:
model.build_vocab(story)

In [19]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

(29411961, 30767745)

In [20]:
len(model.wv.index_to_key)

61843

In [21]:
def document_vector(doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis=0)

In [22]:

document_vector(df['review'].values[0])

array([ 1.77656204e-01, -1.45181298e-01,  1.42617121e-01, -1.65533110e-01,
        5.91126144e-01, -3.05935919e-01, -7.97773451e-02,  3.03686470e-01,
        4.48330432e-01, -2.44083256e-01, -4.19118315e-01, -4.48727727e-01,
       -1.02068275e-01,  3.11583400e-01,  1.37695462e-01,  1.67700067e-01,
        6.81196898e-02, -1.18397161e-01, -5.16915619e-02, -3.37974668e-01,
        1.45469993e-01,  3.62037271e-01, -3.27798396e-01,  3.25750798e-01,
       -1.85639828e-01, -6.65781572e-02, -6.53257370e-02,  9.69033018e-02,
       -4.20497715e-01, -1.91886038e-01,  2.98176974e-01, -3.35941881e-01,
        1.93688825e-01, -3.80960941e-01, -8.89170989e-02,  5.09788215e-01,
       -7.63897002e-02,  6.45966083e-02,  2.06614077e-01, -4.75447893e-01,
       -1.88514978e-01,  9.48951691e-02, -1.52328447e-01, -3.19686323e-01,
        3.34840804e-01, -2.75709599e-01,  6.67713583e-02, -1.20563041e-02,
       -2.21652344e-01,  4.55534786e-01,  4.88388121e-01,  3.34050842e-02,
       -7.93125778e-02, -3.30733061e-01, -4.08982724e-01,  4.24329549e-01,
       -2.07866609e-01,  4.81989950e-01, -1.58535898e-01,  1.18358329e-01,
        1.63845062e-01, -4.36534494e-01,  1.26792380e-04,  1.93864167e-01,
       -8.83859843e-02,  4.04616669e-02, -1.35608315e-01,  8.79916549e-03,
        1.30274743e-01, -1.29473746e-01, -9.26905498e-03, -1.39100671e-01,
        8.34005922e-02, -3.99760872e-01,  3.54590863e-01, -1.38316870e-01,
       -2.30179299e-02, -2.79137939e-01, -3.52164477e-01,  4.61724550e-01,
       -3.86444241e-01, -1.30736604e-01,  7.54796267e-02,  1.33247674e-01,
       -5.62177718e-01, -1.86992854e-01, -2.41478220e-01,  2.25070119e-01,
        5.68851978e-02,  1.85786456e-01,  3.65082443e-01,  7.81697407e-03,
        2.01827884e-01, -2.80162752e-01,  4.05502707e-01,  2.62423515e-01,
       -4.07861024e-02, -5.49587645e-02, -2.45746687e-01,  1.46783680e-01],
      dtype=float32)

In [23]:
from tqdm import tqdm

In [24]:

X = []
for doc in tqdm(df['review'].values):
    X.append(document_vector(doc))

  0%|▎                                                                           | 208/49582 [00:43<2:52:08,  4.78it/s]

KeyboardInterrupt:

In [ ]:
X = np.array(X)

In [ ]:

X[0]

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

y = encoder.fit_transform(df['sentiment'])

In [ ]:

y

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [ ]:

rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)