# One-Hot-Encoding
### 1️⃣ What is One-Hot Encoding?

- One-Hot Encoding is a technique used to convert categorical variables into multiple binary (0/1) columns.

- Each category becomes a separate column, and the value is:

- 1 → category present

- 0 → category absent

- convert each category into one column if we have 50 category then it make 50 columns

- Ohe used on **Nominal Categorical column**

### 3️⃣ Why One-Hot Encoding is Used

- Machine learning models cannot understand text categories.


### 4️⃣ When to Use One-Hot Encoding

- Use it when:

  -  Categories have no order
    
  -  Feature is nominal


### 6️⃣ Dummy Variable Trap ⚠️

- When using One-Hot Encoding, sometimes one column should be dropped to avoid multicollinearity.


### 7️⃣ Advantages
    
    ✅ Prevents false ordering
    
    ✅ Works well for linear models
    
    ✅ Easy to implement

### 8️⃣ Disadvantages

    ❌ Creates many columns (curse of dimensionality)
    ❌ Not efficient for high-cardinality features


### 🔟 One-Line Interview Answer

- One-Hot Encoding converts categorical variables into binary columns so machine learning models can process nominal categorical data without introducing false ordering.

# OHE

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day27-one-hot-encoding/cars.csv"

df = pd.read_csv(url)

df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [2]:
df.shape

(8128, 5)

In [3]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [6]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

# 1.OneHotEncoding using Pandas
-  get_dummy works same as we discuss above about ohe
-  it just pandas function

In [5]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int)
# we have 5 categories in owner and 4 category in  fuel =3 +4+5=12

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

# 2. K-1 OneHotEncoding
- Avoid multicolinarity

In [8]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int,drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

# 3. OneHotEncoding using Sklearn

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
 X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1] , test_size=0.33, random_state=42)

In [11]:
X_train.head()

         brand  km_driven    fuel         owner
4446    Maruti      40000  Diesel   First Owner
2154     Honda      82000  Diesel   First Owner
1344   Renault      81000  Diesel  Second Owner
7856     Honda       6550  Petrol   First Owner
6107  Mahindra      15000  Diesel   First Owner

In [14]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [19]:
ohe=OneHotEncoder(drop='first',dtype=np.int16,sparse_output=False)

In [20]:
X_train_new=ohe.fit_transform(X_train[['fuel','owner']])
X_train_new

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0]], shape=(5445, 7), dtype=int16)

In [21]:
X_train_new.shape

(5445, 7)

In [22]:
X_test_new=ohe.transform(X_test[['fuel','owner']])

In [23]:
X_test_new.shape

(2683, 7)

In [24]:
# merging the data into df

In [27]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Maruti', 40000, 1, ..., 0, 0, 0],
       ['Honda', 82000, 1, ..., 0, 0, 0],
       ['Renault', 81000, 1, ..., 1, 0, 0],
       ...,
       ['Hyundai', 35000, 0, ..., 0, 0, 0],
       ['Maruti', 27000, 1, ..., 0, 0, 0],
       ['Maruti', 70000, 0, ..., 1, 0, 0]], shape=(5445, 9), dtype=object)

# OneHotEncoding with Top Categories
- for avoiding the to many columnns in dataset

In [32]:
counts=df['brand'].value_counts()
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [30]:
df['brand'].nunique()
threshold=100

In [34]:
repl=counts[counts<=threshold].index
repl

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [36]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'),dtype=int).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
30,0,0,0,0,0,0,1,0,0,0,0,0,0
4543,0,0,0,0,0,0,1,0,0,0,0,0,0
7664,0,0,0,0,1,0,0,0,0,0,0,0,0
380,0,0,0,0,0,0,1,0,0,0,0,0,0
4557,0,0,0,0,1,0,0,0,0,0,0,0,0