# 1️⃣ What is Ordinal Encoding?

- Ordinal Encoding is a technique used to convert categorical data with an inherent order (ranking) into numerical values.

- Each category is assigned an integer value based on its order.

- we can identify which category is superier


## Ordinal Encoding only used for indipendent ordinal Categorical data


### 2️⃣ Why Ordinal Encoding is Needed

- Machine learning models cannot work with text values directly, so categorical variables must be converted into numbers.

- Ordinal encoding preserves the order relationship between categories.


### 3️⃣ When to Use Ordinal Encoding

- Use it when categories have a meaningful order.


### 4️⃣ When NOT to Use Ordinal Encoding

- Do not use it for nominal categories (no order).


### 6️⃣ Advantages

  -  ✅ Simple and fast
  -  ✅ Maintains category order
  -  ✅ Works well for tree-based models
        
###7️⃣ Disadvantages

    ❌ Assumes numerical relationship between categories
   
    ❌ Not suitable for nominal features


#### 9️⃣ One-Line Interview Answer

Ordinal Encoding converts ordered categorical variables into numerical values while preserving their ranking relationship.

In [23]:
import pandas as pd

url = "https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day26-ordinal-encoding/customer.csv"

df = pd.read_csv(url)

df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [24]:
df.shape

(50, 5)

In [25]:
df=df.iloc[:,2:]

In [26]:
df.head(3)

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No

# Ordinal Encoder

In [27]:
from sklearn.preprocessing import OrdinalEncoder

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('purchased',axis=1), df['purchased'], test_size=0.33, random_state=42)

In [30]:
X_train.shape,X_test.shape

((33, 2), (17, 2))

In [31]:
# we have to assign order manualy other wise the model choose random order

In [32]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [33]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [44]:
X_train_order=oe.transform(X_train)
X_test_order=oe.transform(X_test)
X_train_order

array([[0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [39]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# Label Encoding
- Label Encoding converts categorical values into numerical labels so machine learning models can process categorical data.

#### label Encoder only used with dependent (target variable) data if data is ordinal catogorical

### When to Use Label Encoding

- Label encoding is best used when:
    
    - The feature is ordinal (has order)
    
    - The column is the target variable (y)


### When NOT to Use Label Encoding

- Avoid it for nominal categories (no order).

### Advantages
    
    ✅ Simple and fast

    ✅ Reduces memory usage

    ✅ Works well for tree-based models

### Disadvantages

    ❌ Introduces false order

    ❌ Can mislead algorithms like KNN, SVM, Linear Regression

* Label Encoder

In [41]:
from sklearn.preprocessing import LabelEncoder

In [45]:
le=LabelEncoder()

In [46]:
le.fit(y_train)

LabelEncoder()

In [48]:
y_train_label=le.transform(y_train)
y_test_label=le.transform(y_test)

In [49]:
y_test

13     No
39     No
30     No
45    Yes
17    Yes
48    Yes
26     No
25     No
32    Yes
19    Yes
12     No
4      No
37    Yes
8      No
3      No
6      No
41    Yes
Name: purchased, dtype: object

In [50]:
y_test_label

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1])

In [51]:
y_train

46     No
47    Yes
15     No
9     Yes
16    Yes
24    Yes
34     No
31    Yes
0      No
44     No
27     No
33    Yes
5     Yes
29    Yes
11    Yes
36    Yes
1      No
21     No
2      No
43     No
35    Yes
23     No
40     No
10    Yes
22    Yes
18     No
49     No
20    Yes
7     Yes
42    Yes
14    Yes
28     No
38     No
Name: purchased, dtype: object

In [52]:
y_train_label

array([0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])