In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst  Unnamed: 32
0    842302         M        17.99  ...          0.4601                  0.11890          NaN
1    842517         M        20.57  ...          0.2750                  0.08902          NaN
2  84300903         M        19.69  ...          0.3613                  0.08758          NaN
3  84348301         M        11.42  ...          0.6638                  0.17300          NaN
4  84358402         M        20.29  ...          0.2364                  0.07678          NaN

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [5]:
df.head()

  diagnosis  radius_mean  texture_mean  ...  concave points_worst  symmetry_worst  fractal_dimension_worst
0         M        17.99         10.38  ...                0.2654          0.4601                  0.11890
1         M        20.57         17.77  ...                0.1860          0.2750                  0.08902
2         M        19.69         21.25  ...                0.2430          0.3613                  0.08758
3         M        11.42         20.38  ...                0.2575          0.6638                  0.17300
4         M        20.29         14.34  ...                0.1625          0.2364                  0.07678

[5 rows x 31 columns]

In [6]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

# Train Test Split

In [8]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

# Scalling

In [9]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [10]:
X_train

array([[-0.81897147, -1.03879207, -0.84827851, ..., -1.47808811,
        -0.11969256, -0.5247562 ],
       [ 2.92570828,  0.52409007,  2.97245473, ...,  2.02801668,
         0.43705281,  0.76204449],
       [ 0.12139654, -0.83025501,  0.01637957, ..., -0.84834716,
        -0.58364705, -1.50884745],
       ...,
       [ 0.14098754,  0.18722251,  0.10000378, ...,  0.7126388 ,
         0.22868028, -0.06897859],
       [-0.27042346,  1.36052993, -0.33191932, ..., -0.81918405,
        -0.72364735, -0.88458062],
       [-0.33199518, -1.16483096, -0.33273121, ..., -0.84272718,
        -0.74318227,  1.0013563 ]], shape=(455, 30))

In [11]:
y_train

333    B
521    M
311    B
8      M
210    M
      ..
130    B
553    B
16     M
457    B
336    B
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [12]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [13]:
y_train

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0])

# Numpy arrays to PyTorch Tensors

In [14]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [15]:
X_test_tensor.shape

torch.Size([114, 30])

In [16]:
y_train_tensor.shape

torch.Size([455])

# Defining The Model

In [18]:
class MySimpleNN():
    def __init__(self,X):
        self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

    def forward(self,X):
        z=torch.matmul(X,self.weights)+self.bias
        y_pred=torch.sigmoid(z)
        return y_pred

    def loss_function(self,y_pred,y):
        # clamp predictions to avoid log(0)
        epsilon=1e-7
        y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

        # calculate loss
        loss=-(y_test_tensor*torch.log(y_pred)+(1-y_test_tensor)*torch.log(1-y_pred)).mean()
        return loss

# Important Parameters

In [19]:
learning_rate =0.1
epochs=25

# Training Pipeline

In [20]:
# create model
model=MySimpleNN(X_test_tensor)

# define loop
for epoch in range(epochs):
    # forward pass
    y_pred=model.forward(X_train_tensor)
    # loss calculate
    loss=model.loss_function(y_pred,y_train_tensor)
    # backward pass
    loss.backward()
    # parameters update
    with torch.no_grad():
        model.weights -=learning_rate*model.weights.grad
        model.bias -= learning_rate*model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f"Epoch:{epoch+1},Loss: {loss.item()}")

Epoch:1,Loss: 3.4742739858939817
Epoch:2,Loss: 3.3312270454553863
Epoch:3,Loss: 3.1866850478492275
Epoch:4,Loss: 3.03920399847745
Epoch:5,Loss: 2.887798233838187
Epoch:6,Loss: 2.7301781551858735
Epoch:7,Loss: 2.5701350430152403
Epoch:8,Loss: 2.40900456177392
Epoch:9,Loss: 2.246398615760639
Epoch:10,Loss: 2.0860374492198
Epoch:11,Loss: 1.9306230262017585
Epoch:12,Loss: 1.7779511321776325
Epoch:13,Loss: 1.6327429388196921
Epoch:14,Loss: 1.495307531063701
Epoch:15,Loss: 1.3714312588859505
Epoch:16,Loss: 1.2623602820381057
Epoch:17,Loss: 1.169071505547812
Epoch:18,Loss: 1.0918326065190718
Epoch:19,Loss: 1.029757710305809
Epoch:20,Loss: 0.980795851835934
Epoch:21,Loss: 0.942328094046663
Epoch:22,Loss: 0.9118424251450132
Epoch:23,Loss: 0.887266028353603
Epoch:24,Loss: 0.8670221729568413
Epoch:25,Loss: 0.8499698792911781

In [21]:
model.bias

tensor([-0.1670], dtype=torch.float64, requires_grad=True)

# Evaluation

In [23]:
# Model Evaluation
with torch.no_grad():
    y_pred=model.forward(X_test_tensor)
    y_pred=(y_pred>0.9).float()
    accuracy=(y_pred==y_test_tensor).float().mean()
    print(f"Accuracy:{accuracy.item()}")

Accuracy:0.6120344996452332