# 1. The Z-Test (One-Sample & Two-Sample)
#### **Scenario:**
#### A factory produces organic tea. The historical population mean weight is 250g with a known standard deviation of 12g. A batch of 40 packets is tested.

#### **A. Manual Formula Fitting (The "Hard" Way)**
We will calculate the Z-score and then find the P-value

In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import math

In [5]:
# step-1: data & parameters
mu=250
sigma=12
n=40
sample_mean=246.5

# --- STEP 2: MANUAL FORMULA FITTING ---
# Formula: Z = (x_bar - mu) / (sigma / sqrt(n))

standard_error=sigma/np.sqrt(n)
z_score=(sample_mean-mu)/standard_error
z_score

np.float64(-1.8446619684315546)

In [18]:
# Manual P-Value Calculation
# For a two-tailed test: 2 * (1 - Area under curve up to Z)
# P(Z>∣z∣)=1−P(Z≤∣z∣)
# p=2×P(Z>∣z∣)
z_standard_value=stats.norm.cdf(abs(z_score))
               
p_value_manual=2*(1-z_standard_value)
print('p_value',p_value_manual,'\n','z standard noramal value',z_standard_value)

p_value 0.06508672649276681
 z standard noramal value 0.9674566367536166

In [7]:
print(f"--- Manual Calculation ---")
print(f"Z-Statistic: {z_score:.4f}")
print(f"P-Value: {p_value_manual:.4f}") 

if p_value_manual < 0.05:
    print("Reject Null Hypothesis")
else:
    print("Accept Null Hypothesis")

--- Manual Calculation ---
Z-Statistic: -1.8447
P-Value: 0.0651
Accept Null Hypothesis

#### **B. Professional Project Approach**
Here, we simulate a dataset of 1,000 packets to show how a Data Scientist handles raw CSV-style data.

In [9]:
# create a realistic dataset
np.random.seed(42)
factory_data=pd.DataFrame({
    'packet_id':range(1,101),
    'weight':np.random.normal(247,12,100),
    'batch':'Batch_A'
})
factory_data.head()

   packet_id      weight    batch
0          1  252.960570  Batch_A
1          2  245.340828  Batch_A
2          3  254.772262  Batch_A
3          4  265.276358  Batch_A
4          5  244.190160  Batch_A

In [20]:
# using Statesmodel for professional Z-test
from statsmodels.stats.weightstats import ztest
z_stat,p_val=ztest(factory_data['weight'],value=250)

print(f"\n--- Professional Approach ---")
print("Z test value:", z_stat)
print("p_value from the test:", p_val,'this is very small number')
print(f"Test Result: {'Reject Null' if p_val < 0.05 else 'Fail to Reject Null'}")

--- Professional Approach ---
Z test value: -3.89626534551862
p_value from the test: 9.768736232205761e-05 this is very small number
Test Result: Reject Null

## Two-Sample Z-Test (Manual & Professional)
#### **Scenario:**
#### Comparing the average test scores of two different coaching centers (Center A and Center B). We know the population standard deviations are 10 and 12 respectively.

In [21]:
# professional data
center_a=np.random.normal(75,10,120)
center_b=np.random.normal(78,12,150)

### 1. Manual Fitting
### Z = (X1bar - X2bar) / sqrt( (sigma1^2/n1) + (sigma2^2/n2) )

In [22]:

mean_a,mean_b=np.mean(center_a),np.mean(center_b)
s1,s2=10,12
n1,n2=len(center_a),len(center_b)

z_2samp=(mean_a-mean_b)/np.sqrt((s1**2/n1)+(s2**2/n2))
z_2samp

np.float64(-1.7210975455643633)

In [25]:
p_2samp=stats.norm.sf(abs(z_2samp))*2
p_2samp

np.float64(0.08523312461366148)

In [26]:
if p_2samp < 0.05:
    print("Reject Null Hypothesis")
else:
    print("Accept Null Hypothesis")

Accept Null Hypothesis

###  2. Professional Approach

In [29]:
z_stats_2,p_val_2=ztest(center_a,center_b)

In [30]:
print(f"Two-Sample Z-Stat: {z_stats_2:.4f}, P-Value: {p_val_2:.4f}")

if p_val_2 < 0.05:
    print("Reject Null Hypothesis")
else:
    print("Accept Null Hypothesis")

Two-Sample Z-Stat: -1.7749, P-Value: 0.0759
Accept Null Hypothesis

# 2. The T-Test (Independent & Paired)
#### **Scenario:** 
#### Testing if a "Memory Booster" supplement works. We compare "Group A" (Placebo) vs "Group B" (Supplement).

## A. Manual Formula Fitting (Independent T-test)

In [32]:
group_a=[20,22,19,21,23]
group_b=[25,28,24,26,27]

# formulas: Mean,variance,Pooled SD and T-scores
mean1,mean2=np.mean(group_a),np.mean(group_b)
var1,var2=np.var(group_a,ddof=1),np.var(group_b,ddof=2)
n1,n2=len(group_a),len(group_b)

# Pooled standard deviation
pooled_se=math.sqrt((var1/n1)+(var2/n2))
t_manual=(mean1-mean2)/pooled_se
t_manual

np.float64(-4.629100498862757)

In [33]:
# Degree of freedom (simplified)
df=n1+n2-2
p_manual=stats.t.sf(abs(t_manual),df)*2

print(f"Manual T-Stat: {t_manual:.4f}, Manual P-Val: {p_manual:.4f}")

if p_manual < 0.05:
    print("Reject Null Hypothesis")
else:
    print("Accept Null Hypothesis")

Manual T-Stat: -4.6291, Manual P-Val: 0.0017
Reject Null Hypothesis

## One-Sample T-Test
#### **Scenario:**

#### A nutritionist claims a new diet reduces weight by 5kg in a month. We test this on 25 people. Since we don't know the population standard deviation, we use T-test.

In [35]:
 # --- PROFESSIONAL DATA ---
weight_loss = np.random.normal(4.2, 1.5, 25) # Small sample, sigma unknown
weight_loss

array([4.23676526, 4.94699744, 6.37671541, 5.63890624, 7.42977369,
       3.04897866, 5.50848096, 4.47501301, 7.4847044 , 2.98755257,
       2.94041724, 3.30091103, 1.01415641, 3.41136747, 3.06130101,
       4.42559068, 4.71263396, 7.01425626, 5.62563576, 3.33464452,
       2.85237799, 4.93787876, 2.21965019, 6.94718815, 5.96916018])

In [38]:
# 1. Manual Fitting
# t = (x_bar - mu) / (s / sqrt(n))
x_bar = np.mean(weight_loss)
mu_claim = 5
s = np.std(weight_loss, ddof=1) # Sample standard deviation
n = len(weight_loss)

In [41]:
t_manual = (x_bar - mu_claim) / (s / np.sqrt(n))
df = n - 1
p_manual = stats.t.sf(abs(t_manual), df) * 2
p_manual

np.float64(0.21357583515131373)

In [42]:
print("T-Test Value:", t_manual)
print("p value:", p_manual)

if p_manual < 0.05:
    print("Reject Null Hypothesis")
else:
    print("Accept Null Hypothesis")

T-Test Value: -1.2777018712938055
p value: 0.21357583515131373
Accept Null Hypothesis

In [43]:
# 2. Professional Approach
t_stat, p_val = stats.ttest_1samp(weight_loss, 5)

In [44]:
print(f"One-Sample T-Stat: {t_stat:.4f}, P-Value: {p_val:.4f}")


if p_val < 0.05:
    print("Reject Null Hypothesis")
else:
    print("Accept Null Hypothesis")

One-Sample T-Stat: -1.2777, P-Value: 0.2136
Accept Null Hypothesis

## Professional Approach for Independent T-Test (Large Data)
#### **Scenario:**
#### A/B Testing for a Website. Does "Blue Button" (A) vs "Red Button" (B) lead to different session times? We have 1000 users in each group.

# CHi- Square Test
- when you wanted to find the significant relationship b/w two categorical variable
- assumtion
  1. data is form of frequency
  2. observation are indipendent
  3. expected frequency in each cell of the contingency table be at least 5

- chi square= (sum of observed freq-excepted freq)**2/expected freq
- like 30,30 ob,15 ,15ex
- =
-

# Chi-Square Test: The "Association" Test
#### **Business Scenario:** 
#### A Marketing Manager wants to know if the Subscription Plan (Basic, Gold, Platinum) chosen by a customer is related to their Region (North, South, East, West). If they are independent, the same marketing strategy works everywhere. If they are dependent, we need regional strategies.1. State the 

**1. HypothesesNull Hypothesis ($H_0$):** Subscription Plan and Region are Independent (No relationship).

**2. Alternative Hypothesis ($H_1$):** Subscription Plan and Region are Dependent (There is a significant relationship).

## A. Theoretical/Manual Calculation (Pen & Paper Logic)

In [4]:
import numpy as np
import pandas as pd
import scipy.stats as stats

observed = np.array([[150, 100, 50],   # North
                     [100, 150, 150]]) # South

# --- MANUAL STEP-BY-STEP ---

# A. Calculate Expected Values: (Row Total * Col Total) / Grand Total
row_totals = observed.sum(axis=1)
col_totals = observed.sum(axis=0)
grand_total = observed.sum()
expected = np.outer(row_totals, col_totals) / grand_total
row_totals,col_totals,grand_total,expected

(array([300, 400]),
 array([250, 250, 200]),
 np.int64(700),
 array([[107.14285714, 107.14285714,  85.71428571],
        [142.85714286, 142.85714286, 114.28571429]]))

In [6]:
# B. Calculate Chi-Square Statistic: sum( (O - E)^2 / E )
chi_sq_manual = np.sum((observed - expected)**2 / expected)
chi_sq_manual

np.float64(56.875)

In [8]:
# C. Calculate Degrees of Freedom (df): (Rows - 1) * (Cols - 1)
df_manual = (observed.shape[0] - 1) * (observed.shape[1] - 1)
df_manual

2

In [9]:
# D. Manual P-Value: Survival Function of chi2 distribution
# This converts our "score" into a probability
p_value_manual = stats.chi2.sf(chi_sq_manual, df_manual)
p_value_manual # it is very-very less

np.float64(4.464272240178803e-13)

In [10]:
print("--- MANUAL RESULTS ---")
print(f"Chi-Square Stat: {chi_sq_manual:.4f}")
print(f"Degrees of Freedom: {df_manual}")
print(f"P-Value: {p_value_manual:.4e}") # Using scientific notation for small values

--- MANUAL RESULTS ---
Chi-Square Stat: 56.8750
Degrees of Freedom: 2
P-Value: 4.4643e-13

In [12]:
if p_value_manual < 0.05:
    print("Reject Null Hypothesis")
else:
    print("Accept Null Hypothesis")

Reject Null Hypothesis

## B. Professional Project Approach (Large Scale)
#### Imagine a dataset with 5,000 customers and 10 different features. We select the two categorical columns and test them.

In [14]:
# Creating a Large Project Dataset
df_marketing = pd.read_csv(r"E:\data\data_set\df_marketing.csv")
df_marketing.head()

  Region      Plan
0   East  Platinum
1   West  Platinum
2  North      Gold
3   East  Platinum
4   East     Basic

In [15]:
# Step 1: Create Contingency Table
contingency_table = pd.crosstab(df_marketing['Region'], df_marketing['Plan'])
contingency_table

Plan    Basic  Gold  Platinum
Region
East      487   430       292
North     520   439       336
South     509   445       286
West      523   423       310

In [16]:
# Step 2: The Scipy approach
chi2, p, dof, expected_table = stats.chi2_contingency(contingency_table)

print("\n--- PROFESSIONAL PROJECT RESULTS ---")
print(f"Chi2 Stat: {chi2:.2f}")
print(f"P-value: {p:.4f}")

# Step 3: Decision Logic
alpha = 0.05
if p < alpha:
    print("Decision: Reject Null Hypothesis (H0).")
    print("Insight: Region and Plan are DEPENDENT. Customize your marketing!")
else:
    print("Decision: Fail to Reject Null Hypothesis (H0).")
    print("Insight: Region and Plan are INDEPENDENT. Use a global strategy.")

--- PROFESSIONAL PROJECT RESULTS ---
Chi2 Stat: 4.05
P-value: 0.6697
Decision: Fail to Reject Null Hypothesis (H0).
Insight: Region and Plan are INDEPENDENT. Use a global strategy.