In [ ]:
import numpy as np
import pandas as pd
import time

In [ ]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "Social_Network_Ads.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "nani123456789/social-network-ads",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

df

/tmp/ipykernel_1950/2212535401.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Downloading to /root/.cache/kagglehub/datasets/nani123456789/social-network-ads/versions/1/Social_Network_Ads.csv...

100%|██████████| 10.7k/10.7k [00:00<00:00, 10.3MB/s]

First 5 records:     User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
df.shape

(400, 5)

In [ ]:
df=df.drop(columns=['User ID','Gender'])

In [ ]:
df

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [ ]:
X=df.iloc[:,0:2]
y=df.iloc[:,-1]

In [ ]:
X.head()

   Age  EstimatedSalary
0   19            19000
1   35            20000
2   26            43000
3   27            57000
4   19            76000

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=scaler.fit_transform(X)

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model=Sequential()
model.add(Dense(10,activation='relu',input_dim=2))
model.add(Dense(10,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 10)             │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 151 (604.00 B)

 Trainable params: 151 (604.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [ ]:
start=time.time()
history=model.fit(X_train,y_train,epochs=500,batch_size=1,validation_split=0.2)
end=time.time()
print("Total time taken: ",end-start)

Epoch 1/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.6055 - loss: 0.6810 - val_accuracy: 0.7812 - val_loss: 0.6297
Epoch 2/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7422 - loss: 0.6070 - val_accuracy: 0.8906 - val_loss: 0.5141
Epoch 3/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8555 - loss: 0.4856 - val_accuracy: 0.9844 - val_loss: 0.3460
Epoch 4/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8828 - loss: 0.3821 - val_accuracy: 0.9844 - val_loss: 0.2460
Epoch 5/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8867 - loss: 0.3362 - val_accuracy: 0.9844 - val_loss: 0.1994
Epoch 6/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8867 - loss: 0.3128 - val_accuracy: 0.9844 - val_loss: 0.1746
Epoch 7/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8789 - loss: 0.3015 - val_accuracy: 0.9844 - val_loss: 0.1596
Epoch 8/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8828 - loss: 0.2960 - val_accuracy: 0.9688 - val_loss: 0.1569
Epoch 9/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8906 - loss: 0.2900 - val_accuracy: 0.9844 - val_loss: 0.1465
Epoch 10/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8906 - loss: 0.2858 - val_accuracy: 0.9688 - val_loss: 0.1482
Epoch 11/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8906 - loss: 0.2849 - val_accuracy: 0.9688 - val_loss: 0.1457
Epoch 12/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8867 - loss: 0.2813 - val_accuracy: 0.9688 - val_loss: 0.1472
Epoch 13/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8867 - loss: 0.2806 - val_accuracy: 0.9688 - val_loss: 0.1415
Epoch 14/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8906 - loss: 0.2793 - val_accuracy: 0.9688 - val_loss: 0.1368
Epoch 15/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8867 - loss: 0.2766 - val_accuracy: 0.9688 - val_loss: 0.1352
Epoch 16/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8906 - loss: 0.2760 - val_accuracy: 0.9688 - val_loss: 0.1386
Epoch 17/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8867 - loss: 0.2757 - val_accuracy: 0.9688 - val_loss: 0.1417
Epoch 18/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8906 - loss: 0.2762 - val_accuracy: 0.9688 - val_loss: 0.1384
Epoch 19/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8828 - loss: 0.2734 - val_accuracy: 0.9688 - val_loss: 0.1450
Epoch 20/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9023 - loss: 0.2734 - val_accuracy: 0.9688 - val_loss: 0.1418
Epoch 21/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8906 - loss: 0.2715 - val_accuracy: 0.9688 - val_loss: 0.1406
Epoch 22/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8906 - loss: 0.2728 - val_accuracy: 0.9688 - val_loss: 0.1384
Epoch 23/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8945 - loss: 0.2714 - val_accuracy: 0.9688 - val_loss: 0.1393
Epoch 24/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8906 - loss: 0.2707 - val_accuracy: 0.9688 - val_loss: 0.1361
Epoch 25/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8984 - loss: 0.2737 - val_accuracy: 0.9688 - val_loss: 0.1402
Epoch 26/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2690 - val_accuracy: 0.9688 - val_loss: 0.1401
Epoch 27/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9023 - loss: 0.2690 - val_accuracy: 0.9688 - val_loss: 0.1364
Epoch 28/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8945 - loss: 0.2689 - val_accuracy: 0.9688 - val_loss: 0.1396
Epoch 29/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8984 - loss: 0.2697 - val_accuracy: 0.9688 - val_loss: 0.1380
Epoch 30/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8945 - loss: 0.2683 - val_accuracy: 0.9688 - val_loss: 0.1360
Epoch 31/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8984 - loss: 0.2673 - val_accuracy: 0.9688 - val_loss: 0.1382
Epoch 32/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2684 - val_accuracy: 0.9688 - val_loss: 0.1407
Epoch 33/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8867 - loss: 0.2683 - val_accuracy: 0.9688 - val_loss: 0.1367
Epoch 34/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8984 - loss: 0.2673 - val_accuracy: 0.9688 - val_loss: 0.1396
Epoch 35/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9023 - loss: 0.2676 - val_accuracy: 0.9688 - val_loss: 0.1386
Epoch 36/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9023 - loss: 0.2655 - val_accuracy: 0.9688 - val_loss: 0.1382
Epoch 37/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9023 - loss: 0.2668 - val_accuracy: 0.9688 - val_loss: 0.1352
Epoch 38/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9023 - loss: 0.2658 - val_accuracy: 0.9688 - val_loss: 0.1357
Epoch 39/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8984 - loss: 0.2664 - val_accuracy: 0.9688 - val_loss: 0.1313
Epoch 40/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8984 - loss: 0.2670 - val_accuracy: 0.9688 - val_loss: 0.1356
Epoch 41/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9023 - loss: 0.2646 - val_accuracy: 0.9688 - val_loss: 0.1392
Epoch 42/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9102 - loss: 0.2659 - val_accuracy: 0.9688 - val_loss: 0.1384
Epoch 43/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8984 - loss: 0.2646 - val_accuracy: 0.9688 - val_loss: 0.1359
Epoch 44/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8945 - loss: 0.2664 - val_accuracy: 0.9688 - val_loss: 0.1341
Epoch 45/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2653 - val_accuracy: 0.9688 - val_loss: 0.1322
Epoch 46/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.9023 - loss: 0.2658 - val_accuracy: 0.9688 - val_loss: 0.1334
Epoch 47/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8984 - loss: 0.2645 - val_accuracy: 0.9688 - val_loss: 0.1397
Epoch 48/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8945 - loss: 0.2653 - val_accuracy: 0.9688 - val_loss: 0.1365
Epoch 49/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9062 - loss: 0.2649 - val_accuracy: 0.9688 - val_loss: 0.1348
Epoch 50/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8984 - loss: 0.2639 - val_accuracy: 0.9688 - val_loss: 0.1348
Epoch 51/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9102 - loss: 0.2643 - val_accuracy: 0.9688 - val_loss: 0.1311
Epoch 52/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8984 - loss: 0.2629 - val_accuracy: 0.9688 - val_loss: 0.1340
Epoch 53/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2644 - val_accuracy: 0.9688 - val_loss: 0.1335
Epoch 54/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2634 - val_accuracy: 0.9688 - val_loss: 0.1360
Epoch 55/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9141 - loss: 0.2638 - val_accuracy: 0.9688 - val_loss: 0.1359
Epoch 56/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9062 - loss: 0.2639 - val_accuracy: 0.9688 - val_loss: 0.1321
Epoch 57/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2645 - val_accuracy: 0.9688 - val_loss: 0.1306
Epoch 58/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9023 - loss: 0.2647 - val_accuracy: 0.9688 - val_loss: 0.1331
Epoch 59/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9023 - loss: 0.2617 - val_accuracy: 0.9688 - val_loss: 0.1327
Epoch 60/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9102 - loss: 0.2618 - val_accuracy: 0.9688 - val_loss: 0.1292
Epoch 61/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9023 - loss: 0.2627 - val_accuracy: 0.9688 - val_loss: 0.1311
Epoch 62/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8945 - loss: 0.2636 - val_accuracy: 0.9688 - val_loss: 0.1344
Epoch 63/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9062 - loss: 0.2658 - val_accuracy: 0.9688 - val_loss: 0.1309
Epoch 64/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9023 - loss: 0.2622 - val_accuracy: 0.9688 - val_loss: 0.1313
Epoch 65/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8984 - loss: 0.2628 - val_accuracy: 0.9688 - val_loss: 0.1337
Epoch 66/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2645 - val_accuracy: 0.9688 - val_loss: 0.1367
Epoch 67/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8984 - loss: 0.2609 - val_accuracy: 0.9688 - val_loss: 0.1317
Epoch 68/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8984 - loss: 0.2618 - val_accuracy: 0.9688 - val_loss: 0.1352
Epoch 69/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8945 - loss: 0.2629 - val_accuracy: 0.9688 - val_loss: 0.1290
Epoch 70/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8984 - loss: 0.2597 - val_accuracy: 0.9688 - val_loss: 0.1370
Epoch 71/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9023 - loss: 0.2647 - val_accuracy: 0.9688 - val_loss: 0.1366
Epoch 72/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9023 - loss: 0.2610 - val_accuracy: 0.9688 - val_loss: 0.1368
Epoch 73/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9023 - loss: 0.2626 - val_accuracy: 0.9688 - val_loss: 0.1331
Epoch 74/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9023 - loss: 0.2614 - val_accuracy: 0.9688 - val_loss: 0.1324
Epoch 75/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8945 - loss: 0.2604 - val_accuracy: 0.9688 - val_loss: 0.1307
Epoch 76/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9023 - loss: 0.2621 - val_accuracy: 0.9688 - val_loss: 0.1321
Epoch 77/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9062 - loss: 0.2612 - val_accuracy: 0.9688 - val_loss: 0.1368
Epoch 78/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8906 - loss: 0.2634 - val_accuracy: 0.9688 - val_loss: 0.1367
Epoch 79/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8984 - loss: 0.2611 - val_accuracy: 0.9688 - val_loss: 0.1319
Epoch 80/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - accuracy: 0.8945 - loss: 0.2599 - val_accuracy: 0.9688 - val_loss: 0.1306
Epoch 81/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9062 - loss: 0.2600 - val_accuracy: 0.9688 - val_loss: 0.1308
Epoch 82/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9102 - loss: 0.2601 - val_accuracy: 0.9688 - val_loss: 0.1356
Epoch 83/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8984 - loss: 0.2585 - val_accuracy: 0.9688 - val_loss: 0.1323
Epoch 84/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9102 - loss: 0.2594 - val_accuracy: 0.9688 - val_loss: 0.1313
Epoch 85/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9102 - loss: 0.2611 - val_accuracy: 0.9688 - val_loss: 0.1329
Epoch 86/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9062 - loss: 0.2593 - val_accuracy: 0.9688 - val_loss: 0.1314
Epoch 87/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9023 - loss: 0.2601 - val_accuracy: 0.9688 - val_loss: 0.1340
Epoch 88/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9062 - loss: 0.2583 - val_accuracy: 0.9688 - val_loss: 0.1298
Epoch 89/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9023 - loss: 0.2595 - val_accuracy: 0.9688 - val_loss: 0.1330
Epoch 90/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9062 - loss: 0.2594 - val_accuracy: 0.9688 - val_loss: 0.1369
Epoch 91/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8984 - loss: 0.2583 - val_accuracy: 0.9688 - val_loss: 0.1315
Epoch 92/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9062 - loss: 0.2583 - val_accuracy: 0.9688 - val_loss: 0.1317
Epoch 93/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9062 - loss: 0.2604 - val_accuracy: 0.9688 - val_loss: 0.1321
Epoch 94/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9023 - loss: 0.2584 - val_accuracy: 0.9688 - val_loss: 0.1265
Epoch 95/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2592 - val_accuracy: 0.9688 - val_loss: 0.1310
Epoch 96/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9062 - loss: 0.2588 - val_accuracy: 0.9688 - val_loss: 0.1322
Epoch 97/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9062 - loss: 0.2576 - val_accuracy: 0.9688 - val_loss: 0.1359
Epoch 98/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8984 - loss: 0.2584 - val_accuracy: 0.9688 - val_loss: 0.1349
Epoch 99/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8984 - loss: 0.2593 - val_accuracy: 0.9688 - val_loss: 0.1327
Epoch 100/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8984 - loss: 0.2568 - val_accuracy: 0.9688 - val_loss: 0.1323
Epoch 101/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9062 - loss: 0.2581 - val_accuracy: 0.9688 - val_loss: 0.1331
Epoch 102/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8984 - loss: 0.2569 - val_accuracy: 0.9688 - val_loss: 0.1324
Epoch 103/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9062 - loss: 0.2572 - val_accuracy: 0.9688 - val_loss: 0.1299
Epoch 104/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2585 - val_accuracy: 0.9688 - val_loss: 0.1342
Epoch 105/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9023 - loss: 0.2582 - val_accuracy: 0.9688 - val_loss: 0.1330
Epoch 106/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8984 - loss: 0.2584 - val_accuracy: 0.9688 - val_loss: 0.1343
Epoch 107/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9062 - loss: 0.2572 - val_accuracy: 0.9688 - val_loss: 0.1289
Epoch 108/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8984 - loss: 0.2580 - val_accuracy: 0.9688 - val_loss: 0.1311
Epoch 109/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8984 - loss: 0.2581 - val_accuracy: 0.9688 - val_loss: 0.1337
Epoch 110/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2569 - val_accuracy: 0.9688 - val_loss: 0.1279
Epoch 111/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8945 - loss: 0.2573 - val_accuracy: 0.9688 - val_loss: 0.1279
Epoch 112/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2574 - val_accuracy: 0.9688 - val_loss: 0.1301
Epoch 113/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2580 - val_accuracy: 0.9688 - val_loss: 0.1315
Epoch 114/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9062 - loss: 0.2567 - val_accuracy: 0.9688 - val_loss: 0.1349
Epoch 115/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2573 - val_accuracy: 0.9688 - val_loss: 0.1302
Epoch 116/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9062 - loss: 0.2565 - val_accuracy: 0.9688 - val_loss: 0.1311
Epoch 117/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2561 - val_accuracy: 0.9688 - val_loss: 0.1351
Epoch 118/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2558 - val_accuracy: 0.9688 - val_loss: 0.1300
Epoch 119/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8984 - loss: 0.2571 - val_accuracy: 0.9688 - val_loss: 0.1270
Epoch 120/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9062 - loss: 0.2566 - val_accuracy: 0.9688 - val_loss: 0.1268
Epoch 121/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9062 - loss: 0.2566 - val_accuracy: 0.9688 - val_loss: 0.1222
Epoch 122/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8984 - loss: 0.2567 - val_accuracy: 0.9688 - val_loss: 0.1297
Epoch 123/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2565 - val_accuracy: 0.9688 - val_loss: 0.1332
Epoch 124/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8984 - loss: 0.2548 - val_accuracy: 0.9688 - val_loss: 0.1265
Epoch 125/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2572 - val_accuracy: 0.9688 - val_loss: 0.1321
Epoch 126/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8984 - loss: 0.2572 - val_accuracy: 0.9688 - val_loss: 0.1304
Epoch 127/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9062 - loss: 0.2557 - val_accuracy: 0.9688 - val_loss: 0.1298
Epoch 128/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9102 - loss: 0.2567 - val_accuracy: 0.9688 - val_loss: 0.1286
Epoch 129/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9102 - loss: 0.2549 - val_accuracy: 0.9688 - val_loss: 0.1307
Epoch 130/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2567 - val_accuracy: 0.9688 - val_loss: 0.1281
Epoch 131/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2552 - val_accuracy: 0.9688 - val_loss: 0.1312
Epoch 132/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8984 - loss: 0.2550 - val_accuracy: 0.9688 - val_loss: 0.1275
Epoch 133/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9023 - loss: 0.2568 - val_accuracy: 0.9688 - val_loss: 0.1237
Epoch 134/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9102 - loss: 0.2557 - val_accuracy: 0.9688 - val_loss: 0.1279
Epoch 135/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9062 - loss: 0.2574 - val_accuracy: 0.9688 - val_loss: 0.1375
Epoch 136/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9102 - loss: 0.2548 - val_accuracy: 0.9688 - val_loss: 0.1300
Epoch 137/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9102 - loss: 0.2549 - val_accuracy: 0.9688 - val_loss: 0.1234
Epoch 138/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9102 - loss: 0.2568 - val_accuracy: 0.9688 - val_loss: 0.1258
Epoch 139/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2576 - val_accuracy: 0.9688 - val_loss: 0.1313
Epoch 140/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9141 - loss: 0.2554 - val_accuracy: 0.9688 - val_loss: 0.1284
Epoch 141/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2544 - val_accuracy: 0.9688 - val_loss: 0.1280
Epoch 142/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8984 - loss: 0.2545 - val_accuracy: 0.9688 - val_loss: 0.1220
Epoch 143/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9062 - loss: 0.2558 - val_accuracy: 0.9688 - val_loss: 0.1272
Epoch 144/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2557 - val_accuracy: 0.9688 - val_loss: 0.1282
Epoch 145/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8984 - loss: 0.2559 - val_accuracy: 0.9688 - val_loss: 0.1305
Epoch 146/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9141 - loss: 0.2541 - val_accuracy: 0.9688 - val_loss: 0.1261
Epoch 147/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8945 - loss: 0.2554 - val_accuracy: 0.9688 - val_loss: 0.1283
Epoch 148/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9062 - loss: 0.2553 - val_accuracy: 0.9688 - val_loss: 0.1265
Epoch 149/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8984 - loss: 0.2549 - val_accuracy: 0.9688 - val_loss: 0.1278
Epoch 150/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9141 - loss: 0.2547 - val_accuracy: 0.9688 - val_loss: 0.1353
Epoch 151/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9023 - loss: 0.2557 - val_accuracy: 0.9688 - val_loss: 0.1349
Epoch 152/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9023 - loss: 0.2565 - val_accuracy: 0.9688 - val_loss: 0.1287
Epoch 153/500
256/256 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9023 - loss: 0.2552 - val_accuracy: 0.9688 - val_loss: 0.1340
Epoch 154/500

In [ ]:
import matplotlib.pyplot as plt
plt.plot(history.history['loss'])