# Multiple Linear Regression
- Multiple Linear Regression (MLR) is a machine learning / statistical technique used to predict a continuous dependent variable using two or more independent variables.

- OR we can Say as:

    - Multiple Linear Regression models the relationship between one dependent variable (Y) and multiple independent variables (X₁, X₂, X₃ … Xₙ).

- Mathematical Equation :

      - Y= b0+b1x1+b2x2+b3x3+....+bnxn

  - Where:

        Y → Dependent variable (target/output)
        
        X₁, X₂, X₃ … → Independent variables (features)
        
        b₀ → Intercept (constant)
        
        b₁, b₂, b₃ … → Coefficients (weights of features)

#### Assumptions of Multiple Linear Regression

       - Linear Relationship between X and Y
        
       - No Multicollinearity (independent variables should not be highly correlated)
        
       - Homoscedasticity (constant variance of errors)
        
       - Normal distribution of residuals
        
       - Independence of observations

       
#### Evaluation Metrics

    - Common metrics used:
    
       - R² Score
        
       - Adjusted R²
        
       - Mean Absolute Error (MAE)
        
       - Mean Squared Error (MSE)
        
       - Root Mean Squared Error (RMSE

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("E:\data\data_set\Investment.csv")

In [4]:
df.head()

   DigitalMarketing  Promotion   Research      State     Profit
0         165349.20  136897.80  471784.10  Hyderabad  192261.83
1         162597.70  151377.59  443898.53  Bangalore  191792.06
2         153441.51  101145.55  407934.54    Chennai  191050.39
3         144372.41  118671.85  383199.62  Hyderabad  182901.99
4         142107.34   91391.77  366168.42    Chennai  166187.94

### Dependent 
- The dependent variable is the output we want to predict.
- Usualy represent (y) in ml
### Independent
- independent variables are the input features used to predict the output.
- usualy repesent (X) in ml

- iloc is used for position-based indexing. It helps quickly select columns when we don't want to type column names or when the target variable is the last column.
- However, using column names is usually clearer in real-world projects.

In [5]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

# One-Hot-Encoding
- It converts categorical variables (text categories) into binary numeric columns (0 and 1).

- pd.get_dummies() performs One-Hot Encoding, a technique used to convert categorical variables into numerical binary columns so that machine learning algorithms can process them.


#### Why It Is Called "One-Hot"

- Because only one column has value = 1 and the rest are 0.

In [6]:
X=pd.get_dummies(X,dtype=int)

In [7]:
X.head()

,DigitalMarketing,Promotion,Research,State_Bangalore,State_Chennai,State_Hyderabad
0,165349.20,136897.80,471784.10,0,0,1
1,162597.70,151377.59,443898.53,1,0,0
2,153441.51,101145.55,407934.54,0,1,0
3,144372.41,118671.85,383199.62,0,0,1
4,142107.34,91391.77,366168.42,0,1,0

In [8]:
y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [12]:
y_pred=reg.predict(X_test)

In [13]:
y_pred

array([126362.87908255,  84608.45383633,  99677.49425146,  46357.46068582,
       128750.48288505,  50912.41741878, 109741.35032702, 100643.24281647,
        97599.27574593, 113097.42524431])

In [14]:
y_test

13    134307.35
39     81005.76
30     99937.59
45     64926.08
17    125370.37
48     35673.41
26    105733.54
25    107404.34
32     97427.84
19    122776.86
Name: Profit, dtype: float64

# Multiple Linear Regression Model Building

In [15]:
m=reg.coef_
m # this coeficient for each features

array([ 8.05630064e-01, -6.87878823e-02,  2.98554429e-02, -3.15260255e+02,
        6.23532751e+02, -3.08272495e+02])

In [16]:
c=reg.intercept_
c

np.float64(54343.29984897953)

In [17]:
X.head()

,DigitalMarketing,Promotion,Research,State_Bangalore,State_Chennai,State_Hyderabad
0,165349.20,136897.80,471784.10,0,0,1
1,162597.70,151377.59,443898.53,1,0,0
2,153441.51,101145.55,407934.54,0,1,0
3,144372.41,118671.85,383199.62,0,0,1
4,142107.34,91391.77,366168.42,0,1,0

- Adding a ones column at the start of X like [1,x1,x2,x3,x4,x5]
- the fill the ones values to 54343

In [18]:
X=np.append(arr=np.ones((50,1)).astype(int),values=X,axis=1)
X=np.append(arr=np.full((50,1),54343).astype(int),values=X,axis=1)

In [19]:
X

array([[5.4343000e+04, 1.0000000e+00, 1.6534920e+05, 1.3689780e+05,
        4.7178410e+05, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 1.6259770e+05, 1.5137759e+05,
        4.4389853e+05, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 1.5344151e+05, 1.0114555e+05,
        4.0793454e+05, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 1.4437241e+05, 1.1867185e+05,
        3.8319962e+05, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 1.4210734e+05, 9.1391770e+04,
        3.6616842e+05, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 1.3187690e+05, 9.9814710e+04,
        3.6286136e+05, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 1.3461546e+05, 1.4719887e+05,
        1.2771682e+05, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 1.3029813e+05, 1.4553006e+05,
        3.2387668e+05, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 1.2054252e+05, 1.4871895e+05,
        3.1161329e+05, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 1.2333488e+05, 1.0867917e+05,
        3.0498162e+05, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 1.0191308e+05, 1.1059411e+05,
        2.2916095e+05, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 1.0067196e+05, 9.1790610e+04,
        2.4974455e+05, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 9.3863750e+04, 1.2732038e+05,
        2.4983944e+05, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 9.1992390e+04, 1.3549507e+05,
        2.5266493e+05, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 1.1994324e+05, 1.5654742e+05,
        2.5651292e+05, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 1.1452361e+05, 1.2261684e+05,
        2.6177623e+05, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 7.8013110e+04, 1.2159755e+05,
        2.6434606e+05, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 9.4657160e+04, 1.4507758e+05,
        2.8257431e+05, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 9.1749160e+04, 1.1417579e+05,
        2.9491957e+05, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 8.6419700e+04, 1.5351411e+05,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 7.6253860e+04, 1.1386730e+05,
        2.9866447e+05, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 7.8389470e+04, 1.5377343e+05,
        2.9973729e+05, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 7.3994560e+04, 1.2278275e+05,
        3.0331926e+05, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 6.7532530e+04, 1.0575103e+05,
        3.0476873e+05, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 7.7044010e+04, 9.9281340e+04,
        1.4057481e+05, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 6.4664710e+04, 1.3955316e+05,
        1.3796262e+05, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 7.5328870e+04, 1.4413598e+05,
        1.3405007e+05, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 7.2107600e+04, 1.2786455e+05,
        3.5318381e+05, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 6.6051520e+04, 1.8264556e+05,
        1.1814820e+05, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 6.5605480e+04, 1.5303206e+05,
        1.0713838e+05, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 6.1994480e+04, 1.1564128e+05,
        9.1131240e+04, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 6.1136380e+04, 1.5270192e+05,
        8.8218230e+04, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 6.3408860e+04, 1.2921961e+05,
        4.6085250e+04, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 5.5493950e+04, 1.0305749e+05,
        2.1463481e+05, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 4.6426070e+04, 1.5769392e+05,
        2.1079767e+05, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 4.6014020e+04, 8.5047440e+04,
        2.0551764e+05, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 2.8663760e+04, 1.2705621e+05,
        2.0112682e+05, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 4.4069950e+04, 5.1283140e+04,
        1.9702942e+05, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 2.0229590e+04, 6.5947930e+04,
        1.8526510e+05, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 3.8558510e+04, 8.2982090e+04,
        1.7499930e+05, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 2.8754330e+04, 1.1854605e+05,
        1.7279567e+05, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 2.7892920e+04, 8.4710770e+04,
        1.6447071e+05, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 2.3640930e+04, 9.6189630e+04,
        1.4800111e+05, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 1.5505730e+04, 1.2738230e+05,
        3.5534170e+04, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 2.2177740e+04, 1.5480614e+05,
        2.8334720e+04, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 1.0002300e+03, 1.2415304e+05,
        1.9039300e+03, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 1.3154600e+03, 1.1581621e+05,
        2.9711446e+05, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 0.0000000e+00, 1.3542692e+05,
        0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 5.4205000e+02, 5.1743150e+04,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [5.4343000e+04, 1.0000000e+00, 0.0000000e+00, 1.1698380e+05,
        4.5173060e+04, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00]])

# Feature Selection
- identify the most usefull features from dataset to create a best model
- We calculate the p-value and eleminates the features if p-value>0.05

# Ordinary Least Square
-

- Ordinary Least Squares (OLS) is a method used in Linear Regression to find the best-fit line for predicting a dependent variable.

- It chooses the line that minimizes the sum of squared differences (errors) between the actual values and the predicted values.
- OLS finds β₀ and β₁ so that prediction error is minimum.

##### Error(Residual)
 - For each data points

    - Residual=Actual-Predicted
    - (ei=yi-yi^) 

##### Why "Squared"?

OLS minimizes:

- sse =(ei=yi-yi^)**2 sum of squared errors

- This is called Sum of Squared Errors (SSE).

- Reasons we square errors:

   - Negative errors become positive
    
   - Large errors are penalized more
    
   - Easier mathematical optimization

### Summary
- Ordinary Least Squares is a statistical technique used in linear regression to estimate model parameters by minimizing the sum of squared residuals between actual and predicted values.

In [ ]:
import statsmodels.api as sm
X_opt=X[:,[0,1,2,3,4,5]]

In [21]:
""" Exogenous variables (independent variables / features).
- Endogenous variable (dependent variable).
- Train an Ordinary Least Squares regression model using y as the target variable and X_opt as the feature matrix."""

regressor_OLS=sm.OLS(endog=y,exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Fri, 06 Mar 2026   Prob (F-statistic):           8.51e-29
Time:                        14:07:58   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.9230      0.125      7.377      0.000       0.671       1.175
x1          1.698e-05    2.3e-06      7.377      0.000    1.23e-05    2.16e-05
x2             0.8057      0.046     17.646      0.000       0.714       0.898
x3            -0.0268      0.052     -0.520      0.606      -0.131       0.077
x4             0.0272      0.017      1.627      0.111      -0.006       0.061
x5           -70.2265   2828.752     -0.025      0.980   -5767.625    5627.172
==============================================================================
Omnibus:                       14.785   Durbin-Watson:                   1.281
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.242
Skew:                          -0.949   Prob(JB):                     2.44e-05
Kurtosis:                       5.568   Cond. No.                     5.16e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.5e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

# Backward Elimination (Feature Selection)

- Backward Elimination is a feature selection technique used with Ordinary Least Squares (OLS) regression to remove statistically insignificant variables from a model.

- It uses p-values from statsmodels OLS results to decide which feature should be removed.

#### Algorithm Steps

- Start with all independent variables

- Fit OLS regression

- Check p-values

- Remove the variable with highest p-value

- Refit the model

- Repeat until all p-values < 0.05

In [32]:
import statsmodels.api as sm
X_opt=X[:,[0,1,2,3,5]] #remove the 4 feature
# ols
regressor_ols=sm.OLS(endog=y,exog=X_opt).fit()
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.948
Model:                            OLS   Adj. R-squared:                  0.944
Method:                 Least Squares   F-statistic:                     278.7
Date:                Fri, 06 Mar 2026   Prob (F-statistic):           1.68e-29
Time:                        14:40:59   Log-Likelihood:                -526.82
No. Observations:                  50   AIC:                             1062.
Df Residuals:                      46   BIC:                             1069.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.0138      0.114      8.896      0.000       0.784       1.243
x1          1.866e-05    2.1e-06      8.897      0.000    1.44e-05    2.29e-05
x2             0.8613      0.031     27.974      0.000       0.799       0.923
x3            -0.0528      0.050     -1.058      0.296      -0.153       0.048
x4          -502.8903   2866.249     -0.175      0.861   -6272.350    5266.570
==============================================================================
Omnibus:                       14.294   Durbin-Watson:                   1.184
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               19.252
Skew:                          -0.956   Prob(JB):                     6.60e-05
Kurtosis:                       5.364   Cond. No.                     5.98e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.41e-22. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [27]:
import statsmodels.api as sm 
X_opt=X[:,[0,1,2,3]] # remove the 5 feature
# ols
regressor_ols=sm.OLS(endog=y,exog=X_opt).fit()
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.948
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     426.8
Date:                Fri, 06 Mar 2026   Prob (F-statistic):           7.29e-31
Time:                        14:16:25   Log-Likelihood:                -526.83
No. Observations:                  50   AIC:                             1060.
Df Residuals:                      47   BIC:                             1065.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.0100      0.111      9.122      0.000       0.787       1.233
x1          1.859e-05   2.04e-06      9.122      0.000    1.45e-05    2.27e-05
x2             0.8621      0.030     28.589      0.000       0.801       0.923
x3            -0.0530      0.049     -1.073      0.289      -0.152       0.046
==============================================================================
Omnibus:                       14.678   Durbin-Watson:                   1.189
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               20.449
Skew:                          -0.961   Prob(JB):                     3.63e-05
Kurtosis:                       5.474   Cond. No.                     8.04e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.88e-22. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [28]:
import statsmodels.api as sm
X_opt=X[:,[0,1,3]] # remove the 2 feature
# ols
regressor_ols=sm.OLS(endog=y,exog=X_opt).fit()
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.040
Model:                            OLS   Adj. R-squared:                  0.020
Method:                 Least Squares   F-statistic:                     2.015
Date:                Fri, 06 Mar 2026   Prob (F-statistic):              0.162
Time:                        14:18:18   Log-Likelihood:                -599.63
No. Observations:                  50   AIC:                             1203.
Df Residuals:                      48   BIC:                             1207.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.4165      0.466      3.040      0.004       0.480       2.353
x1          2.607e-05   8.57e-06      3.040      0.004    8.83e-06    4.33e-05
x2             0.2887      0.203      1.419      0.162      -0.120       0.698
==============================================================================
Omnibus:                        0.126   Durbin-Watson:                   0.099
Prob(Omnibus):                  0.939   Jarque-Bera (JB):                0.110
Skew:                           0.093   Prob(JB):                        0.947
Kurtosis:                       2.866   Cond. No.                     6.70e+18
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.04e-26. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [29]:
import statsmodels.api as sm
X_opt=X[:,[0,1]] # remove the 3 fature
# ols
regressor_ols=sm.OLS(endog=y,exog=X_opt).fit()
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                       nan
Date:                Fri, 06 Mar 2026   Prob (F-statistic):                nan
Time:                        14:18:58   Log-Likelihood:                -600.65
No. Observations:                  50   AIC:                             1203.
Df Residuals:                      49   BIC:                             1205.
Df Model:                           0
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.0612      0.105     19.651      0.000       1.850       2.272
x1          3.793e-05   1.93e-06     19.651      0.000    3.41e-05    4.18e-05
==============================================================================
Omnibus:                        0.018   Durbin-Watson:                   0.020
Prob(Omnibus):                  0.991   Jarque-Bera (JB):                0.068
Skew:                           0.023   Prob(JB):                        0.966
Kurtosis:                       2.825   Cond. No.                     1.89e+20
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.15e-30. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

# Bias  (High Bias)= Underfitting
- Bias is the difference between the model’s expected prediction and the true value due to incorrect assumptions in the learning algorithm.

- Bias is the error that occurs when a model is too simple to capture the true patterns in the data.

  -  High bias: The model oversimplifies, misses patterns and underfits the data.
  -  Low bias: The model captures patterns well and is closer to the true values.

- Bias^2= (predicted -actual)**2


# Variance (High Variance)=Overfitting
- Variance is the error caused by the model’s sensitivity to small fluctuations in the training data. High variance leads to overfitting.
- It fails to give prediction on unseen new data.
- High variance: The model is too sensitive to small changes and may overfit.
- Low variance: The model is more stable but might miss some patterns.