# Regularization
- Regularization is a technique used in machine learning to prevent overfitting by adding a penalty term to the loss function so that the model does not become too complex.

 **It is commonly used in models like:**

    Linear Regression
    
    Logistic Regression
    
    Support Vector Machine
    
    Neural Networks using Weight Decay

In [59]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
- Data preprocessing is the process of cleaning, transforming, and preparing raw data into a structured format suitable for machine learning algorithms.

# Feature Scaling

- Feature Scaling is a data preprocessing technique used in Machine Learning to bring all features (variables) to a similar scale or range. 📊

- Many ML algorithms (like Linear Regression, KNN, SVM, Gradient Descent) work better when the input features have similar magnitudes.

# PolynomialFeatures
- PolynomialFeatures is a preprocessing technique used to convert linear features into polynomial features so that a linear model can learn non-linear relationships.

- It is commonly used in Polynomial Regression, which extends Linear Regression to model curved relationships.

# Ridge Regression
- Ridge Regression is a regularized version of Linear Regression that helps reduce overfitting by adding a penalty on large coefficients.

- Ridge Regression is a regularization technique that adds an L2 penalty to the loss function to shrink model coefficients and reduce overfitting.

- Advantages of Ridge Regression

✔ Reduces overfitting
✔ Handles multicollinearity
✔ Improves model stability
✔ Works well with many features

- Disadvantages

❌ Does not perform feature selection
❌ All features remain in the model

# Lasso Regression
- Lasso Regression is a regularization technique used to reduce overfitting and perform feature selection in regression models.

- Advantages of Lasso

✔ Reduces overfitting
✔ Performs automatic feature selection
✔ Produces simpler models
✔ Useful for high-dimensional data

- Disadvantages

❌ If features are highly correlated, Lasso may randomly select one and remove others
❌ May remove useful features in some cases

# R2_score
- R² Score is a statistical metric that measures how well a regression model explains the variance in the dependent variable.

In [60]:
from sklearn import preprocessing
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.metrics import r2_score

In [61]:
df=pd.read_csv("E:\data\data_set\car-mpg.csv")

In [62]:
df.head()

,mpg,cyl,disp,hp,wt,acc,yr,origin,car_type,car_name
0,18.0,8,307.0,130,3504,12.0,70,1,0,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,0,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,0,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,0,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,0,ford torino

In [63]:
df=df.drop('car_name',axis=1)

In [64]:
df

      mpg  cyl   disp   hp    wt   acc  yr  origin  car_type
0    18.0    8  307.0  130  3504  12.0  70       1         0
1    15.0    8  350.0  165  3693  11.5  70       1         0
2    18.0    8  318.0  150  3436  11.0  70       1         0
3    16.0    8  304.0  150  3433  12.0  70       1         0
4    17.0    8  302.0  140  3449  10.5  70       1         0
..    ...  ...    ...  ...   ...   ...  ..     ...       ...
393  27.0    4  140.0   86  2790  15.6  82       1         1
394  44.0    4   97.0   52  2130  24.6  82       2         1
395  32.0    4  135.0   84  2295  11.6  82       1         1
396  28.0    4  120.0   79  2625  18.6  82       1         1
397  31.0    4  119.0   82  2720  19.4  82       1         1

[398 rows x 9 columns]

In [65]:
df['origin']=df['origin'].replace({1:'america',2:'europe',3:'asia'})

In [66]:
df.head()

    mpg  cyl   disp   hp    wt   acc  yr   origin  car_type
0  18.0    8  307.0  130  3504  12.0  70  america         0
1  15.0    8  350.0  165  3693  11.5  70  america         0
2  18.0    8  318.0  150  3436  11.0  70  america         0
3  16.0    8  304.0  150  3433  12.0  70  america         0
4  17.0    8  302.0  140  3449  10.5  70  america         0

In [67]:
df=pd.get_dummies(df,columns=['origin'],dtype=int)

In [68]:
df # convert catogorical data into numrical data

,mpg,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,18.0,8,307.0,130,3504,12.0,70,0,1,0,0
1,15.0,8,350.0,165,3693,11.5,70,0,1,0,0
2,18.0,8,318.0,150,3436,11.0,70,0,1,0,0
3,16.0,8,304.0,150,3433,12.0,70,0,1,0,0
4,17.0,8,302.0,140,3449,10.5,70,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,1,0,0
394,44.0,4,97.0,52,2130,24.6,82,1,0,0,1
395,32.0,4,135.0,84,2295,11.6,82,1,1,0,0
396,28.0,4,120.0,79,2625,18.6,82,1,1,0,0
397,31.0,4,119.0,82,2720,19.4,82,1,1,0,0

In [69]:
df=df.replace('?',np.nan)

In [70]:
df=df.apply(pd.to_numeric,errors='ignore')
df=df.apply(lambda x:x.fillna(x.median()) if x.dtype!='object' else x)

C:\Users\USER\AppData\Local\Temp\ipykernel_10512\2784710816.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df=df.apply(pd.to_numeric,errors='ignore')

In [71]:
df.isnull().sum()

mpg               0
cyl               0
disp              0
hp                0
wt                0
acc               0
yr                0
car_type          0
origin_america    0
origin_asia       0
origin_europe     0
dtype: int64

In [72]:
X=df.drop(['mpg'],axis=1)
y=df[['mpg']]

In [73]:
X_s=preprocessing.scale(X)
X_s   # scale the values to near the zero

array([[ 1.49819126,  1.0906037 ,  0.67311762, ...,  0.77355903,
        -0.49764335, -0.46196822],
       [ 1.49819126,  1.5035143 ,  1.58995818, ...,  0.77355903,
        -0.49764335, -0.46196822],
       [ 1.49819126,  1.19623199,  1.19702651, ...,  0.77355903,
        -0.49764335, -0.46196822],
       ...,
       [-0.85632057, -0.56103873, -0.53187283, ...,  0.77355903,
        -0.49764335, -0.46196822],
       [-0.85632057, -0.70507731, -0.66285006, ...,  0.77355903,
        -0.49764335, -0.46196822],
       [-0.85632057, -0.71467988, -0.58426372, ...,  0.77355903,
        -0.49764335, -0.46196822]], shape=(398, 10))

In [74]:
X_s=pd.DataFrame(X_s,columns=X.columns)
X_s.head()

,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,1.498191,1.090604,0.673118,0.630870,-1.295498,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
1,1.498191,1.503514,1.589958,0.854333,-1.477038,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
2,1.498191,1.196232,1.197027,0.550470,-1.658577,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
3,1.498191,1.061796,1.197027,0.546923,-1.295498,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
4,1.498191,1.042591,0.935072,0.565841,-1.840117,-1.627426,-1.062235,0.773559,-0.497643,-0.461968

In [75]:
y_s=preprocessing.scale(y)
y_s[0]

array([-0.7064387])

In [76]:
y_s=pd.DataFrame(y_s,columns=y.columns)
y_s.head()

        mpg
0 -0.706439
1 -1.090751
2 -0.706439
3 -0.962647
4 -0.834543

In [77]:
X

,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,8,307.0,130.0,3504,12.0,70,0,1,0,0
1,8,350.0,165.0,3693,11.5,70,0,1,0,0
2,8,318.0,150.0,3436,11.0,70,0,1,0,0
3,8,304.0,150.0,3433,12.0,70,0,1,0,0
4,8,302.0,140.0,3449,10.5,70,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,1,1,0,0
394,4,97.0,52.0,2130,24.6,82,1,0,0,1
395,4,135.0,84.0,2295,11.6,82,1,1,0,0
396,4,120.0,79.0,2625,18.6,82,1,1,0,0
397,4,119.0,82.0,2720,19.4,82,1,1,0,0

In [78]:
X_train, X_test, y_train, y_test = train_test_split(X_s, y_s, test_size=0.20, random_state=0)

In [79]:
reg=LinearRegression()

In [80]:
reg.fit(X_train,y_train)

LinearRegression()

# ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [81]:
regression_coeficient=reg.coef_
regression_coeficient

array([[ 0.24638776,  0.29177092, -0.18081622, -0.66755306,  0.06537309,
         0.34817703,  0.33392313, -0.08117985,  0.06986098,  0.03000316]])

In [82]:
ridge=Ridge(alpha=0.4)
ridge.fit(X_train,y_train)

Ridge(alpha=0.4)

In [83]:
ridge_coef=ridge.coef_
ridge_coef

array([ 0.24242411,  0.28008024, -0.18071842, -0.65711583,  0.06353256,
        0.34721777,  0.32998816, -0.08077573,  0.06989674,  0.02945199])

In [86]:
lasso=Lasso(alpha=0.4)
lasso.fit(X_train,y_train)
lasso_coef=lasso.coef_
lasso_coef

array([-0.        , -0.        , -0.02607759, -0.37882273,  0.        ,
        0.04317192,  0.0073939 , -0.        ,  0.        ,  0.        ])